import pandas as pd

# Cargar el archivo CSV
#df = pd.read_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv")

df = pd.read_csv("G:\\Mi unidad\\2024\\Msc. Alberto León Batallas\\nuevoarticulo\\artículo final\\data\\wos_scopus_reemplazado.csv")
   # Lista de palabras clave a eliminar (en minúsculas)
palabras_clave_a_eliminar = [

    "article", "priority journal", "nonhuman", "human", "humans", "animals", "animal", "animal experiment", 
    "animal tissue", "animal cell", "animal model", "animalia", "male", "female", "physiology", "metabolism", 
    "genetics", "gene expression regulation", "gene expression", "messenger rna", "protein expression", 
    "protein function", "protein degradation", "proteins", "recombinant protein", "recombinant proteins", 
    "unclassified drug", "drug effect", "drug activity", "pharmacological blocking", "chronic stress", 
    "obesity", "hydrocortisone", "corticosterone", "cortisol", "hypothalamo‑hypophyseal system", 
    "pituitary‑adrenal system", "blood", "plasma interactions", "hormone", "estradiol", 
    "adrenocorticotropic hormone", "lightemitting diode", "antennas", "spectroscopy", 
    "eigenvalues and eigenfunctions", "antennas", "biochemistry", "biosynthesis", "cell culture", 
    "cell cycle", "cell proliferation", "rna messenger", "rna small interfering", "rna interference", 
    "glucose", "glucocorticoid receptor", "immunology", "immunoglobulin enhancer binding protein", 
    "nerve cell", "neurons", "neural networks", "rat", "rats", "mouse", "mice", "wistar rat", 
    "sprague‑dawley rat", "muscle contraction", "nerve tissue", "animal experiment", "yeast", 
    "saccharomyces cerevisiae", "escherichia coli", "bacteria", "bacterial infections", 
    "viral infections", "embryo", "embryo development", "pregnancy", "diabetes", "insulin", 
    "hemolysis", "hyperphagia", "hyperthermia", "immunosuppressive treatment", "clinical evaluation", 
    "major clinical study", "protein binding", "receptor protein", "receptors glucocorticoid", 
    "receptors androgen", "receptors vasopressin", "cytokine", "cytokinesis", "apoptosis", 
    "immunization", "vaccination", "osteogenesis", "arthritis rheumatoid", "neuropeptide Y", 
    "neuropeptides", "nitric oxide synthase", "oxidative stress", "gene silencing", "mutation", 
    "nucleotide sequence", "apoptosis", "antigen presenting cell", "enzyme inhibition", 
    "enzyme activation", "enzyme phosphorylation", "enzyme repression", "estrus cycle", "placenta", 
    "fetus", "newborn", "child", "adolescent", "adult", "metabolic rate", "thyroid function", 
    "kidney", "liver", "lung ventilation", "cardiovascular disease", "cardiac surgery", 
    "brain structures", "hippocampus", "neurotransmission", "synaptic transmission", 
    "mental stress", "psychological stress", "depression", "neurodegenerative disease", 
    "amyotrophic lateral sclerosis", "tumor necrosis factor‑alpha", "oncology", "carcinoma", 
    "leukemia", "obesity management", "diet", "nutrition", "food intake", "agricultural robots", 
    "plant proteins", "plant root nodulation", "photosynthesis", "algae", "chlorella vulgaris", 
    "coral reefs", "marine biology", "environmental monitoring", "sediment transport", "erosion", 
    "coastal morphology", "sea‑level rise", "meteorology", "ozone", "greenhouse gases", 
    "solar cells", "solar panels", "wind power", "wave propagation", "sound absorbing materials", 
    "acoustics", "sonar", "holographic interference", "virtual reality", "video games", "art", 
    "participatory art", "cultural studies", "geopolitical issues", "diplomacy", 
    "historical reconstruction", "philosophy", "ethics", "review", "procedure", "property", 
    "condition", "function", "analysis", "design", "performance", "application", "engineering", 
    "method", "algorithm", "simulation", "computer simulation", "numerical method", 
    "experimental validation", "theoretical study", "case control study", 
    "data interpretation statistical", "database", "matlab", "ns-2 simulation", "algebra", 
    "equation", "time factor", "cost", "cat disease", "alcoholism", "care", "medication", 
    "dna", "rna", "enzyme", "mice knockout", "swine", "cattle", "fish", "bird", "alga", 
    "computer software", "internet", "computer network", "reliability", "quality control", 
    "safety", "accident prevention", "environmental protection", "economic and social effect", 
    "education", "law", "management", "work", "student", "teacher", "atomic force microscopy", 
    "atomic force microscope", "genetic", "biological model", "human cell", "reverse transcriptase polymerase chain reaction", 
    "reverse transcription polymerase chain reaction", "corticotropin", "hypotalamo‑hypophyseal system", 
    "baroreflex", "4 aminobutyric acid", "arterial pressure", "body motion", 
    "corticotransferin (corticotropin)", "homeostasis", "hypophysis–adrenal system", 
    "pituitary adrenal system", "protein–protein interaction", "reverse transcriptase polymerase chain reaction",
    "cell line (e.g. HEK293)", "blood pressure regulation", "hormone release", 
    "enzymatic activity (e.g. adenosine triphosphate)", "neurotransmitter (e.g. GABA)", 
    "peptide/protein biosynthesis", "temperature", "antenna", "aircraft detection", 
    "aircraft control", "drone", "flight control system", "flight environment", 
    "flight simulator", "unmanned aerial vehicle uav", "unmanned ground vehicle", 
    "collision avoidance", "environmental condition", "hard disk drive", "decay organic", 
    "degree of freedom mechanic", "hsub sub control", "nano positioner", "non square plant", 
    "non square system", "operational amplifier", "smart actuator", "microlense", 
    "micro lens actuator", "micro optic", "natural frequency", "wave filter", 
    "settling time", "pressoreceptor reflex", "orbit", "orbital", "orbit control", 
    "satellite", "satellite orbital system", "air vehicle", "quadcopter unmanned aerial vehicle",
    "power transmission line", "electric power system control", "electrical power system", 
    "electric load flow", "computer circuit", "threshold voltage",
    "1 4‑dihydro‑2 6‑dimethyl 5 nitro 4 2‑trifluoromethylphenyl 3 pyridinecarboxylic acid methyl ester",  
    "2 3 4 5 tetrahydro‑7 8 dihydroxy 1 phenyl 1H‑3 benzazepine",  
    "2 deoxy 6 N‑methyladenosine 3 5‑bisphosphate",  
    "2 methylthioadenosine diphosphate",  
    "2 morpholino 8 phenylchromone",  
    "3 4 dihydroxyphenylacetic acid",  
    "4‑aminobutyric acid A receptor blocking agent",  
    "4‑aminobutyric acid A receptor stimulating agent",  
    "5′ untranslated region",  
    "8‑chloro 2 3 4 5‑tetrahydro 3 methyl 5 phenyl 1H‑3 benzazepin‑7‑ol hydrogen maleate",  
    "90 nm CMOS",  
    "acetazolamide",  
    "acetyltransferase",  
    "actin filament",  
    "adenosine triphosphatase potassium",  
    "adrenalectomy",  
    "adrenergic alpha antagonist",  
    "aircraft accident",  
    "alanine",  
    "alcohol withdrawal",  
    "alpha adrenergic receptor blocking agent",  
    "anabolic steroid",  
    "anaphase promoting complex cytosome",  
    "angiogenesis",  
    "animal welfare",  
    "aplysia californica",  
    "arterial baroreflex",  
    "atrial fibrillation",  
    "aerospace vehicle",  
    "autonomic nervous system",  
    "blood pressure measurement",  
    "bone marrow",  
    "brain stem injury",  
    "cerebrovascular circulation",  
    "chaos theory",  
    "chemotaxis leukocyte",  
    "cholesterol",  
    "chronic obstructive pulmonary disease",  
    "circuit fault",  
    "cytotoxic T lymphocyte antigen 4",  
    "diabetes mellitus type 2",  
    "DNA binding protein",  
    "ecotoxicology",  
    "electrochemical impedance spectroscopy",  
    "fluorescence microscopy",  
    "follitropin receptor",  
    "GABAergic transmission",  
    "hematopoiesis",  
    "hemodynamic",  
    "HPA axis",  
    "hyperandrogenemia",  
    "immunofluorescence",  
    "inflammation mediator",  
    "ionotropic receptor",  
    "juvenile diabetes",  
    "keratinocyte",  
    "lipopolysaccharide",  
    "lysosomal enzyme",  
    "microbiome",  
    "microfluidic",  
    "molecular genetic",  
    "neuropeptide Y",  
    "neutrophil extracellular trap",  
    "oncogene",  
    "pancreatic islet",  
    "peptide",  
    "pharmacokinetics",  
    "plasma interaction",  
    "polymorphism single nucleotide",  
    "porous material",  
    "proteome",  
    "radiotherapy dosage",  
    "ribosome",  
    "RNA seq",  
    "serotonin agonist",  
    "spliceosome",  
    "stem cell",  
    "synaptic inhibition",  
    "tubuloglomerular feedback",  
    "ubiquitination",  
    "ultrastructure",  
    "vasopressin blood level",  
    "Western blotting",  
    "whole cell patch clamp",
    "4 aminobutyric acid",  
    "adenosine diphosphate",  
    "arginine",  
    "artery",  
    "blood pressure",  
    "cell communication",  
    "cell function",  
    "circadian rhythm",  
    "culture medium",  
    "dose response relationship drug",  
    "escherichia coli",  
    "fluorescein",  
    "fluorescent dye",  
    "gene expression regulation developmental",  
    "gene regulatory network",  
    "genetic transfection",  
    "glycerol",  
    "glycine",  
    "granulosa cell",  
    "green fluorescent protein",  
    "high performance liquid chromatography",  
    "hpa axis",  
    "hyperplasia",  
    "hypophysis",  
    "hypothalamus hypophysis adrenal system",  
    "hypoxia",  
    "neutrophil",  
    "nitric oxide",  
    "peptide",  
    "polyclonal antibody",  
    "potassium channel blocking agent",  
    "presynaptic inhibition",  
    "protein interaction",  
    "protein protein interaction",  
    "radioimmunoassay",  
    "reactive oxygen metabolite",  
    "rna small interfering",  
    "saccharomyce cerevisiae",  
    "spermine",  
    "spermicide",  
    "stress psychological",  
    "testosterone",  
    "transaction",  
    "transcription regulation",  
    "veterinary",
    "be simulation",  
    "flow of fluid",  
    "fluid flow model",  
    "hek293 cell",  
    "heterogeneous system",  
    "knowledge base system",  
    "learning system",  
    "molecular dynamic",  
    "mus",  
    "packet level",  
    "oestradiol",  
    "run",
    "atlas", "nyquil", "mem", "lei", "luis", "hard disk storage", "tube component", "fast tcp", "do gain", 
    "hypothalamus hypophyseal system", "feedback biochemical", "convergence of numerical method", 
    "design and implementation", "engineering application", "model biological", "laser", "electromechanical device", 
    "large scale system", "hopf bifurcation", "micro lens",
    "1 4 dihydro 2 6 dimethyl 5 nitro 4 2 trifluoromethylphenyl 3 pyridinecarboxylic acid methyl ester",
    "2 3 4 5 tetrahedron-7 8 hydroxy a phenyl the a benzazepine", "2 3 4 5 tetrahydro 7 8 dihydroxy 1 phenyl 1h 3 benzazepine", 
    "2 deoxy 6 n methyladenosine 3 5 bisphosphate", "2 methylthioadenosine diphosphate", "2 morpholino 8 phenylchromone", 
    "3 4 dihydroxyphenylacetic acid", "3 dof helicopter", "3d interface", "3d modeling", "3d printing", "3d visualization", 
    "4 aminobutyric acid a receptor blocking agent", "4 aminobutyric acid a receptor stimulating agent",
    "5 untranslated region", "8 chloro 2 3 4 5 tetrahydro 3 methyl 5 phenyl 1h 3 benzazepin 7 ol hydrogen maleate", 
    "90 nm cmos", "a", "a aminopyrine", "a analysis", "a case", "a casein", "a controllability", "a d modeling", 
    "a learning", "a methylthio add", "a pm pl system",
    "a pyridinecarboxylic acid 1 4 hydro-2 6 methyl a nitro a a trifluoromethylphenyl- methyl ester", "a stable", 
    "a station", "absolute error", "absorption", "ac converter", "ac microgrid", "accurate estimation", "accurate location", 
    "acoustic", "acoustic interaction", "acoustic neurinoma", "acoustic noise", "acoustic wave propagation", 
    "acoustical performance", "acromegaly", "actin filament", "action potential", "activator inhibitor system", 
    "active control system", "active filter", "active matrix",
    "active matrix organic light emitting diode amole", "active part", "active vibration control", "actuation voltage", 
    "actuator dynamic", "actuator performance", "adaptation physiological", "adaptive alternating positive and negative feedback", 
    "adaptive differential evolution algorithm", "adaptive management", "adaptive nonlinear control", "adaptive radiation therapy", 
    "adaptive trajectory", "adaptor protein signal transducing", "adeline", "adenosine", "adenosine monophosphate", 
    "adenosine triphosphatase potassium", "adenovirus", "adjusting method", "admittance", "adrenal gland", "adrenal hyperplasia", 
    "adrenalin", "adrenergic alpha antagonist", "adrenergic beta antagonist", "adrenergic system", "aerial robotic", 
    "aerial vehicle", "aeromonas salmonicida", "aerospace vehicle", "affective computing", "afferent arteriole", 
    "afferent pathway", "again", "age", "age factor", "aggregation method", "aggression", "agouti relate protein", 
    "air navigation", "air traffic control", "air traffic management", "aircraft accident", "aircraft communication", 
    "alcohol dependence", "alcohol drinking", "alcohol withdrawal", "all", "all fiber", "allostasis", 
    "alpha adrenergic receptor blocking agent", "alpha adrenergic receptor stimulating agent", "alternative approach", 
    "altitude control", "altitude disease", "ambulatory ecmo", "amfebutamone plus naltrexone", "amine oxidase flavin containing", 
    "amino acid receptor affecting agent", "amino acid sequence", "amino acid transport", "ampakine", "amplifier electronic", 
    "amplitude modulation", "anabolic steroid", "analog circuit", "analysis and simulation", "analysis and synthesis", 
    "analysis method", "analysis of stability", "analysis of variance", "analytical framework", "anaphase promoting complex cyclosome", 
    "anatomic model", "androgene blood level", "androgen receptor", "androstanolone", "angiotensin ii", "angular distribution", 
    "angular velocity", "animal welfare", "annulation", "anoxic sediment", "antennal mechanosensation", "anti-16 aircraft", 
    "anti bacterial activity", "antiandrogen", "antimicrobial resistance", "aorta arch", "aplasia", "aplysia californica", 
    "application program", "application range", "approximate inversion", "approximate solution", "approximation", 
    "approximation process", "approximation theory", "ar c67085mx", "ar drone quadcopter", "arabidopsis", "arginine vasopressin", 
    "argipressin", "aromatase inhibitor", "arp", "art computing", "artefact", "arterial baroreflex", "arterial carbon dioxide tension", 
    "arterial pressure regulation", "arteriole", "artery constriction", "arthritis rheumatoid", "arthropod antennae", 
    "artificial membrane", "artificial system", "as", "assimilation efficiency", "asymptotic", "asymptotic analysis", 
    "asymptotic convergence", "at", "atlantic salmon", "atomic force microscope afm", "atp release", 
    "attention deficit disorder with hyperactivity", "attention deficit hyperactivity disorder", "attitude motion", 
    "attitude stabilization", "audio frequency amplifier", "auto focus", "auto focusing", "autocrine effect", "autoimmunity", 
    "automatic current control", "automatic power control", "automatic train control", "automobile body", "autonomous microgrid", 
    "autoregulation of nodulation", "auxiliary output", "azobenzene", "bacterial cell", "bacterial colonization", 
    "bacterial infection", "bacterium culture", "balanced truncation", "bandwidth requirement", "baroreflex function", 
    "basal ganglia", "basic helix loop helix transcription factor", "be", "be requisites", "be stress", "beam", "beamforming", 
    "beat phenomenon", "bench mark problem", "benchmark model", "benzoylarginine ethyl ester", 
    "beta gamma dichloromethylene 2 propylthioadenosine triphosphate", "bicmos operational transconductance amplifier", 
    "bicuculline", "bifurcation", "bilinear matrix", "binding protein", "binding site", "bioaccumulation", "biochemical analysis", 
    "biochemical control", "biochemical network", "biochemical system", "biofouling", "biological clock", "biological function", 
    "biological network", "biological rhythm", "biological science", "biological system", "biological uptake", "biomechanic", 
    "biosensor", "bipolar transistor", "bistable dissipative soliton", "bk channel interacting protein 1", "bladder contraction", 
    "bladder muscle", "blending", "blood circulation", "blood flow", "blood glucose", "blood pressure determination", 
    "blood pressure measurement", "blood sampling", "bluff body flame", "bluff body flame holder", "body attitude", 
    "body build", "body fat", "body position", "body temperature", "body weight", "body weight control", "body weight loss", 
    "boer goat", "bond strength chemical", "boost converter", "boost convertor", "bos tauru", "bottleneck link", 
    "bound positive real bpr", "bovine serum albumin", "bra", "brain circulation", "brain slice", "brain stem injury", 
    "brain structure", "brake", "brandt ishlinskii model", "breathing pattern", "breeding", "bridge cable", "bridge retrofitting", 
    "bridge superstructure", "broad frequency range", "bruun rule", "buck", "buck converter", "building blocke", "bumetanide", 
    "butcher", "cabdriver", "cadmium", "caenorhabditis elegan", "caenorhabditis elegans protein", "calcium channel", 
    "calcium channel l type", "calcium channel stimulating agent", "calcium chloride", "calcium signaling", "calvin", 
    "camera", "camp", "cantilever beam", "capacitor", "capacity", "capillary pressure", "capra hircus", 
    "carbon dioxide arc welding", "carbon monoxide", "carboxy terminal sequence", "cardiology", "cardiovascular simulation", 
    "cardiovascular surgery", "carotid sinus", "carrier protein", "cat", "catalysis", "catastrophe theory", "catch up growth", 
    "cavity dynamic", "cavity system", "cd positive lymphocyte", "cd4 antigen", "cd69 antigen", "cdh1 protein", "cell activity", 
    "cell aging", "cell biology", "cell contact", "cell death", "cell differentiation", "cell engineering", "cell isolation", 
    "cell lysate", "cell mechanic", "cell membrane", "cell migration", "cell polarity", "cell population", "cell shape", 
    "cell stimulation", "cell synchronization", "cell volume", "cellular context", "cellular senescence", "cellular stress", 
    "center manifold and normal form", "center of gravity", "center of gravity cog", "central apnea", "central nervous system", 
    "central pattern generation", "centre of gravity", "cerebrovascular circulation", "chaos", "chaos theory", "chaotic dynamic", 
    "characteristic response pattern", "checkpoint", "chelate", "chelating agent", "chemical activation", "chemical analysis", 
    "chemical mechanical polishing", "chemical reaction", "chemical system", "chemokine cxcl10", "chemoreceptor", 
    "chemoreceptor feedback", "chemotaxis leukocyte", "children", "chlorella vulgaris", "chloride", "chronic disease", 
    "chronic obstructive pulmonary disease copd", "chronic otitis media", "circuit fault", "circuit theory", "circulation", 
    "city", "civil engineering", "class d amplifier", "classical method", "clavata 3 endosperm root signal 1", "cliff", 
    "cliffe coast", "clonal anergy", "clonidine", "close loop experiment", "close loop model", "close loop performance", 
    "cluttered environment", "cmos technology", "cmos voltage reference", "co", "co locate", "co sub 2 /sub arc welding machine", 
    "coastal erosion", "coastal evolution", "coastal zone", "codon", "codon terminator", "coherent control", 
    "collaborative structure", "collision free trajectory", "collocate structure", "color", "combustion", 
    "combustion instability", "combustor", "commercial aircraft", "communication base train control cbtc system", 
    "comparative study", "compensation", "compensation personnel", "compensation scheme", "complex dielectric constant", 
    "complex function", "complex ginzburg landau equation", "complex modulus", "complex modulus of elasticity", "compliance", 
    "composite micromechanic", "compressibility", "computational advantage", "computational complexity", "computational modelling", 
    "computational simulation", "computational system", "compute online", "computer control system", "computer system", 
    "concentration composition", "conceptual framework", "conditional stability", "conditioning", 
    "congenital central hypoventilation syndrome", "consensus algorithm", "constant speed wire feeding", "constraint theory", 
    "continous time", "continue fraction", "continuous time modeling", "control allocation", "control application", 
    "control architecture", "control chip", "control circuit", "control engineering", "control equipment", "control mechanism", 
    "control module", "control nonlinearity", "control of atomic force microscope", "control principle", "control synthesis", 
    "control system analysis", "control system design", "control system modeling", "controllability", "conventional method", 
    "conventional pid", "convergence property", "converse theorem", "converter station", "converter system", "convex relaxation", 
    "convex synthesis", "cooperative communication", "cooperative task", "cooperative tracking", "cooperative tracking control", 
    "core temperature", "corpus striatum", "correlation analysis", "corticosterone blood level", "corticotropin release", 
    "corticotropin releasing factor", "corticotropin releasing factor receptor 1", "cos", "cost effectiveness", 
    "counter clockwise", "couple system", "coupler", "coupling effect", "coupling transformer", "critical care", 
    "critical short circuit ratio cscr", "cross diffusion", "cross point", "cross sectional study", "crossflow filtration", 
    "crowding", "cryopreservation", "crystal", "cubic quintic nonlinearity", "current limiting", "current mode control", 
    "current regulation", "current source", "current transfer function", "curve fitting", "curve fitting approximation", 
    "cyclic amp", "cyclin d1", "cycling", "cycling dependent kinase 4", "cytotoxic t lymphocyte antigen 4", "damped structure", 
    "damper", "damping property", "dan", "dan binding protein", "dare", "dark soliton", "data acquisition", 
    "data drive control", "data drive controller", "data support", "dc distribution system", "dc loop", "dc machinery", 
    "dc micro grid", "dc microgrid", "dc reference voltage", "decay rate", "decentralise integral controllability", 
    "decomposition method", "decontrol", "deep brain stimulation", "delay endolymphatic hydrop", "delay feedback", 
    "delay system", "delighting", "delta sigma modulator", "department of experimental medicine", "deposition", 
    "depressive disorder major", "derivative method", "dermis", "design and implement", "design approach", "design control", 
    "design framework", "design implementation", "design method", "design methodology", "design parameter", "design principle", 
    "destabilizing effect", "detector", "detoxification", "development", "dexamethasone", "dexamethasone suppression test", 
    "dextran", "diabete mellitus", "diabete mellitus experimental", "diabete mellitus type 2", "diagnosis", 
    "diagonal dominant matrix", "dielectric property", "difference matrix", "difference operator", "different mechanism", 
    "differential formulation", "diffuser optical", "diffusion", "diffusion in liquid", "digital analog converter", 
    "digital camera", "digital radio", "digital signal", "digital signal processing", "digital to analog converter", 
    "digital tube display", "digitization", "dihydrotestosterone", "dimethyl sulfoxide", "diplomatic relation", "direct graph", 
    "directional information", "disability", "disaster", "discrete time analysis", "discrete time positive real system", 
    "dispersion wave", "displacement sensor", "dissipative dynamic", "dissipative property", "dissipative soliton", 
    "dissipative system", "dissipativeness", "dissipativity property", "distribute control", "distribute energy resource", 
    "distribute formation control", "distribute generating", "distribute generation unit", 
    "distribute leaderfollower formation control", "distribute obstacle avoidance approach", 
    "distribute parameter control system", "distribute parameter network", "distribute power generation", 
    "distribute unmanned aerial vehicle uav formation control", "distribution network", "divider", "dna complementary", 
    "do ac inverter", "do dc buck converter", "do dc converter", "do link voltage", "door", "dopamine", "dopaminergic system", 
    "dose", "dose accumulation", "dose calculation", "dose distribution", "dose estimation", "dose response relationship", 
    "dosimetry", "double complex adaline algorithm", "double integrator", "dq reference frame", "drain current", 
    "drinking behavior", "driving parameter", "drug cost", "drug derivative", "drug efficacy", "drug inactivation", 
    "drug synergism", "drug synthesis", "dstatcom", "dual axis rotation", "dual band", "dual output", "dual stage", 
    "dual stage hdd", "dynamic behaviour", "dynamic change", "dynamic controller", "dynamic equilibrium", "dynamic model", 
    "dynamic output feedback", "dynamic output feedback control", "dynamic performance", "dynamic property", 
    "dynamic surface control", "dynamic variation", "dysthymia", "dysthymic disorder", "ear surgery", "economical compensation", 
    "ecto 5 nucleotidase", "ecuador", "educational building", "effective damping", "egg-19 protein c elegan", "eigenvalue analysis", 
    "eigenvalue loci", "elastic modulus", "elastic wave", "electric battery", "electric charge", "electric conductivity", 
    "electric control equipment", "electric equipment protection", "electric load", "electric load dispatching", "electric power grid", 
    "electric power system", "electric power system interconnection", "electric power system measurement", 
    "electric power system protection", "electric power transmission", "electric power transmission network", 
    "electric power utilization", "electric sensing device", "electric stimulation", "electric traction", "electric utility", 
    "electrical engineering", "electrical impedance spectroscopy", "electrical power", "electrify railway", 
    "electrochemical analysis", "electrode", "electromagnetic field theory", "electromagnetic mode", "electromagnetic simulation", 
    "electromagnetic wave scattering", "electromyogram", "electromyography", "electronic component", "electronic device", 
    "electronic system", "electrophysiology", "element method", "embryology", "embryophyta", "emission spectroscopy", 
    "end stage lung disease", "endanger specie", "endocannabinoid", "endocrine disease", "endolymphatic hydrop", 
    "endolymphatic sac", "endoplasmic reticulum", "endothelial nitric oxide synthase", "endothelium cell", "energy balance", 
    "energy bound disturbance", "energy conservation", "energy conversion", "energy dissipation", "energy efficiency", 
    "energy expenditure", "energy optimization", "energy saving measure", "engineering field", "engineering practitioner", 
    "engineering research", "engineering science", "enteric feeding", "enterocyte", "environmental effect", "environmental regulation", 
    "environmental uncertainty", "enzyme activity", "enzyme modification", "enzyme substrate", "epifluorescence microscopy", 
    "epigenetic", "epinephrine", "equilibrium", "equipment", "equivalence class", "equivalent open loop function", 
    "erythrocyte membrane", "estradiol blood level", "estrogen deficiency", "etc", "ethylene", "euler lagrange equation", 
    "evaluation and improvement", "evaporation", "evaporation section", "even value", "evolutionary algorithm", "evolutionary game", 
    "exact numerical solution", "excitatory postsynaptic potential", "exciton", "existence and uniqueness", "existence result", 
    "exocytosis", "experimental realization", "explicit formulation", "explicit solution", "explosion", "exponentially stable", 
    "extend gershgorin theorem", "extend interaction", "external perturbation", "external prestressing", "external vibration", 
    "externally positive linear system", "extracellular fluid", "extracellular trap", 
    "extracorporeal co sub 2 /sub removal ecco sub 2 /sub r", "extracorporeal membrane oxygenation ecmo", "eye tracking", 
    "failure tolerance", "fampridine", "faraday effect", "fast gradient method", "fasting induce hyperphagia", "fault condition", 
    "feasibility of lighting system", "feasibility study", "feed back loop", "feed through", "feedback connection", 
    "feedback problem", "feedback signal", "feedback stabilization", "feeding", "feeding behavior", "feeding circuit", "feline", 
    "fibroblast", "fictive axis emulation", "fictive axis emulation fae", "field programmable gate array fpga", "finasteride", 
    "finite dimensional", "finite element method", "finite time", "fire fighting equipment", "first principle", "fish disease", 
    "fishery", "fitness function", "fix point", "fix time", "fk 506 binding protein", "fk506 binding protein 5", 
    "fk506 binding protein 5 gene", "flexible beam", "flexible manipulator integral resonant control", "flexible spacecraft", 
    "flight control", "flight guidance system", "flow rate", "fluorescence", "fluorescence analysis", "fluorescence microscopy", 
    "flying", "follitropin receptor", "footprint of uncertainty", "footprint of uncertainty fou", "force", "force and torque", 
    "formation containment control", "forward compensator", "fouling", "fractional differentiator of complex order", 
    "fractional integrator", "fractional integrator of complex order", "fractional null", "fractional order", 
    "fractional order calculus", "fractional order controller", "fractional order derivative", "fractional order system", 
    "fractional order transfer function", "frameshifting ribosomal", "frequency compensation technique", "frequency control", 
    "frequency dependent gain bind", "frequency domain", "frequency domain data", "frequency dynamic", "frequency estimation", 
    "frequency modulation", "frequency synthesizer", "full state feedback", "function evaluation", "function property", 
    "functional requirement", "fundamental frequency", "fungal strain", "fungus growth", "fuzzy control", "fuzzy logic", 
    "g c kennedy", "gabaergic system", "gabaergic transmission", "gain", "gain analysis", "gain dispersion", "gain measurement", 
    "gain stability", "game theory", "gamma aminobutyric acid", "ganglia invertebrate", "ganglia spinal", "ganglion", 
    "gap junction", "gaussian white noise", "gaza", "gaza a receptor agonist", "gaze stabilization reflex", "gene activation", 
    "gene deletion", "gene expression profiling", "gene expression regulation fungal", "gene expression regulation plant", 
    "gene induction", "gene overexpression", "gene regulatory network model", "gene repression", "gene switch", "gene synthetic", 
    "gene vector", "general anesthesia", "generalize nyquist criterion", "generation", "genetic analysis", "genetic association", 
    "genetic code", "genetic enhancement", "genetic parameter", "genetic regulation", "genetic transcription", "genetic vector", 
    "genotype", "gentamicin", "geometric and material property", "geopolitic", "ghz", "gird strength", "global positioning system", 
    "global stability", "glomerulus capillary", "glomerulus filtration", "glucagon like peptide 1 receptor agonist", "glucocorticoid", 
    "glucocorticoid induce tumor necrosis factor receptor", "glucose tolerance test", "glutamatergic signaling", "glutamine", 
    "glutathione", "goal performance discrepancy", "gonadotropin", "good compatibility", "gram negative bacterial infection", 
    "great blood vessel", "green alga", "green computing", "gremlin", "grid connect converter", "grid connection", 
    "grid forming control", "grid infrastructure", "ground vehicle", "group formation", "group theory", 
    "growth development and aging", "growth inhibition", "guidance and control system", "gyro free", 
    "h static output feedback", "h sub /sub model order reduction", "h sub 1 /sub -performance", "h sub 8 /sub control", 
    "h8 control", "habituation psychophysiologic", "haemolysis", "hard disk drive hdd", "hard disk drive servo system", 
    "hardware implementation", "harmonic cancellation", "harmonic compensation", "harmonic suppression", "harmonic voltage", 
    "have", "he performance", "head", "head positioning", "heart", "heart cycle", "heart denervation", 
    "heart leave ventricle function", "heart muscle contractility", "heart rate", "heart ventricle pressure", 
    "heat shock stress protein", "heat stress", "heavy ion", "hela cell", "helicopter", "helix wave", "heredity", 
    "heterogeneous power system", "high altitude periodic breathing", "high concentration", "high dose", "high frequency", 
    "high frequency dynamic", "high order", "high order soliton", "high order system", "high osmolarity glycerol", 
    "high performance technique", "high plant", "high speed imaging", "high stability", "high voltage", "hill function", "hog", 
    "holographic interference fringe", "holographic recording", "homogeneous ugvs cooperation", "horizontal drilling", 
    "hormone determination", "hormone substitution", "host pathogen interaction", "hpi axis", "human computer interaction", 
    "human induce vibration", "hungary", "hunger", "hvdc power transmission", "hybrid and alternative drive vehicle", 
    "hybrid control", "hybrid integrator gain system hig", "hybridization genetic", "hydroelectric generator", 
    "hydroelectric power", "hyperandrogenism", "hypercapnia", "hypernodulation aberrant root formation receptor protein 1", 
    "hyperpolarization", "hypertrophy", "hypothalamus pituitary adrenal axis", "hypothalamus ventromedial nucleus", 
    "hypothermia", "iberiotoxin", "identification scheme", "ideology", "illustrative example", "image enhancement", 
    "imaging application", "imaging system", "imidacloprid", "immobilization stress", "immunization secondary", 
    "immunocytochemistry", "immunohistochemistry", "immunologic surveillance", "immunoreactivity", "immunoregulation", 
    "immunosurveillance", "impedance", "impedance characteristic", "impedance load", "impedance matching electric", 
    "impedance measurement", "impedance network model", "impedance ratio", "impedance return difference matrix", "implant", 
    "implementation structure", "imrt delivery", "in", "in network", "in plant operation", "inactivation metabolic", 
    "inc-2 protein c elegan", "incompatibility", "independent control", "inductance", "induction motor load", 
    "inertia free attitude stabilization", "inertial measurement unit", "infection", "infection control", 
    "infinite dimensional system", "inflammation", "inflammation mediator", "inflammatory stimulus", "influence", 
    "influencing factor", "information management", "inhibitory postsynaptic potential", "initial condition", "innate immunity", 
    "inner ear", "inner loop", "innervation", "inoculation", "input output data", "input output negative imaginary ioni system", 
    "input output stability", "insect protein", "insect vision", "insecticide", "insulin growth factor 1", 
    "insulin like growth factor binding protein igfbp", "integral component", "integral control", "integral controller", 
    "integral force feedback", "integral sliding mode control", "integrate", "integrate circuit", "integrate circuit design", 
    "integrate circuit manufacture", "integrodifferential equation", "intelligence", "intelligent control", "intelligent structure", 
    "intensity modulate radiation therapy", "intensive care unit", "interactive computer graphic", "interactive media", 
    "interactivity", "interconnection system", "interconnection topology", "interference fringe", "interferon", "interferon a", 
    "interferon gamma", "interlocking signal", "internal dynamic", "international relation", "internet of thing", 
    "interpersonal relation", "interval system", "interval type fuzzy", "intestine cell", "intracellular signaling", 
    "intrinsic parameter", "intro", "inverse", "inverse feedforward", "inverse problem", "inverse response", "inverter base", 
    "investment", "ion channel", "islet of langerhan", "isolation procedure", "isopentenyltransferase", "isoprenaline", 
    "isoproterenol", "it", "italy", "iteration interval", "its application", "jugular vein", "k sub atp /sub channel", 
    "kalman filter", "kalmanyakubovicpopov", "kalmar yakubovic popov lemma", "ketoacidosis", "kidney tubule function", 
    "knockout mouse", "koopman operator", "kronecker product", "l 2 gain", "l2 stability", "laboratory model", 
    "laboratory simulation", "lagrange multiplier", "landform", "landing phase", "laplacian matrix", "lar", 
    "large conductance calcium activate potassium channel alpha subunit", 
    "large conductance can sup 2 /sup -sensitive k sup /sup channel maxik channel", "large scale", "large vehicle", "larva", 
    "laser beam", "laser beam stabilization", "laser feedback", "laser pulse", "laser sensor", "laser theory", "lateral hypothalamus", 
    "law of physic", "lead lag compensator", "leader following", "leader following consensus", "learning ability", 
    "learning algorithm", "learning capability", "learning in game", "learning technique", "legume", 
    "lei base multi objective synthesis", "leptin", "leuprorelin", "license", "light absorption", "light control glass", 
    "light emitting diode", "light transmission", "lighting fixture", "lighting system", "lightweight", "linear ccd", 
    "linear controller", "linear dynamic", "linear feedback control", "linear model", "linear modeling", "linear output", 
    "linear quadratic gaussian control", "linear quadratic regulator", "linear stability", "linear stability analysis", 
    "linear time invariant plant", "linear transformation", "linearisation", "linearization", "linearize stability analysis", 
    "liporegulatory substance exchange in parabiosis", "lipostatic hypothesis", "live load", "lmi approach", "load branch", 
    "load dynamic", "load harmonic", "localize dissipation", "localize synthesis", "lock in amplifier", "locus ceruleus", 
    "locus coeruleus", "locust", "locusta migratoria", "logic gate", "logistic", "long term exposure", "longitudinal direction", 
    "longitudinal mode", "loop diuretic agent", "loop filter", "loop formula", "loop function", "loop gain measurement", 
    "loss factor", "loss integrator", "loss of agent", "lossy integrator", "lotus", "low complexity", "low frequency instability", 
    "low frequency oscillation", "low pass filter", "low power", "low temperature polycrystalline oxide ltpo", 
    "low voltage multi terminal dc distribution system", "luminance", "luminescence of organic solid", "lump torsional system", 
    "lumpfish cyclopterus lumpus l", "lung circulation", "luteinizing hormone", "lyapunov 's function", "lymphocyte activation", 
    "machine component", "machine design", "machine vibration", "machinery", "magnesium chloride", "magnetic field bias", 
    "magnetic gain", "magnetic leakage", "magnetic permeability", "magnetic sensor", "maintenance", "maintenance therapy", 
    "major histocompatibility antigen class 2", "malnutrition", "mammal", "mammalian", "mammary gland", "mandela", 
    "mass conservation", "mass spectrometry", "mathematical analysis", "mathematical computing", "mathematical modeling", 
    "mathematical parameter", "mathematical transformation", "matlab /simulink", "matlab software package", "matrix", 
    "matrix inequality", "maximum power point tracker", "maxwell equation", "mean squared error", "measurement information", 
    "measurement noise", "mechanic", "mechanical feedback", "mechanical model", "mechanical wave", "mechanism", "mechanization", 
    "mechanotransduction", "mechatronic", "mediator", "medical problem", "medium and high frequency", "medulla oblongata", 
    "membership function", "membrane filter", "membrane potential", "membrane protein", "meniere be disease", "meniere disease", 
    "mesangial cell", "mesangium cell", "metal", "metamaterial", "methicillin resistant staphylococcus aureus", "methodology", 
    "michelson interferometer", "micro", "micro grid", "microactuator", "microanalysis", "microbiology", "microcontroller", 
    "microfiltration", "micromechanic", "micromechanical device", "micron", "micron-155", "microoptic", "microrna 155", 
    "microwave filter", "military application", "milk down regulation", "mimo communication", "mimo dynamical system", 
    "mimo phase response", "mineralocorticoid receptor", "miniature endplate potential", "minimal state", "minimum phase", 
    "mirror", "mitogen activate protein kinase 1", "mitosis", "mixed negative imaginary ni and small gain approach", "mixing", 
    "mobile application", "mobility compensating", "mode reduction", "model base observer", "model base technique", 
    "model cardiovascular", "model neurological", "model parameter", "model predictive controller", "model reduction method", 
    "model reference adaptive control", "model structure", "modeling and simulation", "modeling uncertainty", 
    "modelling and analysis", "modern instrument", "modify rodrigue parameter", "molecular genetic", "monitoring tool", 
    "monoamine oxidase", "monoclonal antibody cd3", "morphogenesis", "mos get", "mos transistor", "moses", "most", "moth", 
    "motion", "motion tracking control", "motivation", "motor control", "motor disorder", "motor neuron", "motor system", 
    "movement", "moving block signaling mbs system", "moving block signaling system", "mrna stability", "multi agent control algorithm", 
    "multi band", "multi converter", "multi input multi output case", "multi input multi output communication", 
    "multi input multi output control", "multi input multi output nonlinear system", "multi input multi output plant", 
    "multi layered", "multi loop control system", "multi objective synthesis", "multi reference", "multi scale", "multi terminal", 
    "multi tilt tricopter", "multi uav", "multi uav system", "multi variable velocity feedback controller", "multi variables system", 
    "multilane", "multilevel process", "multimodal integration", "multiobjective optimization", "multiple grid connect converter system", 
    "multiple mobile robot", "multiple train network", "multiplexer", "multivalent", "multivariable control system", 
    "multivariable integral", "muscimol", "muscle protein", "muscle smooth", "muscle sympathetic nerve activity", "musical instrument", 
    "mutant", "myosin ii", "myosin light chain", "n ethoxycarbonylmethyl 6 methoxyquinolinium bromide", 
    "n methyl dextro aspartic acid receptor", "n methyl dextro aspartic acid receptor stimulating agent", 
    "n6 methyl 2 deoxyadenosine 3 5 diphosphate", "nan positioning stage", "nano mechatronic system", "nano scale", 
    "nano system", "nanocantilever", "nanofiber", "nanopositioning", "nanotechnology", "natural process", 
    "navigation in formation", "navigation system", "negative control", "negative feedback circuit", "negative feedback control", 
    "negative imaginary control", "negative imaginary controller", "negative imaginary ni uncertainty", "negative imaginary property", 
    "negative imaginary theorem", "negative imaginary uncertainty", "neonate", "neonicotinoid", "nerve cell inhibition", 
    "nerve cell membrane conductance", "nerve conduction", "nerve net", "network", "network aggregation", "network graph", 
    "network modeling", "network negative imagi nary system", "neural fuzzy controller", "neural inhibition", 
    "neural network control", "neural network model", "neuron afferent", "neuropeptide", "neuropeptide y", "neurotransmitter release", 
    "neutrophil extracellular trap", "new application", "nitro compound", "nitro derivative", "nitroprusside", "nmda receptor", 
    "no methyl of deoxyadenosine 3 5'-phosphate", "nodule inception protein", "noise", "noise control application", "nominal model", 
    "nominal value", "non- fragile control", "non-local non-linearity", "non cooperative target", "non diagonal dominant matrix", 
    "non existence", "non fragile", "non fragile control", "non hamiltonian", "non insulin dependent diabete mellitus", 
    "non linear optimisation", "non linear optimization", "non monotonicity", "non trivial", "non trivial task", 
    "nonholonomic wheeled mobile robot", "noninvasive medical procedure", "noninvasive method", "nonlinear dynamic", 
    "nonlinear feedback", "nonlinear negative imaginary property", "nonlinear optic", "nonlinear slope constraint", 
    "nonlinear strictly negative imaginary theory", "nonlocal nonlinear media", "nonrem sleep", "norway", "nucleolus", 
    "nucleotide", "null allele", "number theory", "numerical analysis", "numerical control", "numerical controlled oscillator", 
    "numerical optimization", "numerical result", "numerous model", "nutrient absorption", "nyquist criteria", "nyquist plot", 
    "nyquist stability criterion", "observer base control", "obstacle avoidance", "oestrogen", "of a", "off chip", 
    "oleander hawkmoth daphnis nerii", "olfactory nerve", "olfactory receptor neuron", "on chip", "one dimensional", 
    "one dimensional lattice system", "online computation", "online identification", "online system", "onto mechanical sensor", 
    "oocyte", "open reading frame", "operating region", "operation amplifier", "operation condition", 
    "operational transconductance amplifier", "operon", "optical cavity", "optical communication", "optical delay time", 
    "optical material", "optical path difference", "optical recording", "optical resonator", "optical zooming", "optimal control", 
    "optimal control system", "optimal controller", "optimal feedback gain", "optimal state", "optimal static output feedback", 
    "optimization algorithm", "optimization method", "optimize performance", "orbital model", "ordinary people", 
    "organ transplantation", "organic light emitting diode ole", "organogenesis", "original system", "oscillating flow", 
    "oscillation suppression", "oscillator mechanical", "oscillometry", "osmoregulation", "osmosis", "osmotic stress", 
    "other property", "otologic surgical procedure", "outdoor operation", "output consensus", "output feedback controller", 
    "output frequency", "output impedance", "output injection", "output level", "output phase", "output pulse", "output signal", 
    "output strictpassivity", "ovariectomy", "ovary follicle", "ovary function", "ox 40 protein", "oxidation", "oxygen", 
    "oxygen transport", "pancrea islet", "parabiosis", "parallel inductor", "parameter perturbation", "parameter self adjusting", 
    "parameter sensitivity", "parasitic bipolar", "parasympathetic tone", "paraventricular nucleus", "pargyline", "park", 
    "park vector", "parkinson 's disease", "partial fraction expansion", "particle swarm optimization pso", 
    "particle swarm optimization pso algorithm", "passenger comfort", "passive and ni system", "passive network", 
    "passivity analysis", "patch clamp", "patient model", "patient modeling", "patient treatment", "pattern matching", 
    "payload sway motion control", "pc", "peak amplitude", "perceptive threshold", "performance index", "performance measure", 
    "periodic oscillation", "periodic phenomenon", "periodic solution", "periodicity", "permanent magnet", "permanent magnetic", 
    "permittivity", "peroxide", "phase detector", "phase modulation", "phase modulation suppression", "phase noise", 
    "phase signal", "phase stabilization", "phase theory", "phase transition", "phenotype", "phentermine", "phentolamine", 
    "phosphatidylinositol 3 kinase", "phosphoprotein", "photo oncogene protein", "photon", "photon correlation spectroscopy", 
    "photonic band gap", "photonic crystal", "photovoltaic module", "phrase", "physical connection", "physical device", 
    "physical effect", "physical equipment", "physical network", "physical system", "physical therapy", "physiological function", 
    "physiological model", "physiological noise", "phytochelatin", "pia mater", "pid control", "pid parameter", 
    "piecewise linear system", "piecewise linear technique", "piezoelectric bimorph", "piezoelectric cantilever", 
    "piezoelectric ceramic", "piezoelectric sensor", "piezoelectric tube", "piezoelectric tube scanner pt", "piglet", 
    "pipeline a d converter", "pitch attitude", "pitch motion", "pithapf", "pituitary adenoma", "pixel", "planning procedure", 
    "plant genetically modify", "plant model", "plant parameter", "plant protein", "plant shoot", "plant signaling and development", 
    "plasmid vector", "plasmonic", "platoon control", "pm", "poincaremap", "polarization", "pole placement", 
    "pole placement control", "pollution exposure", "polo like kinase 1", "polycrystalline oxide", "polymer",
    "polymerization", "polymorphism single nucleotide", "polynomial", "polytopic uncertain"

]

# Función para eliminar palabras clave específicas y retornar una cadena
def eliminar_palabras_clave(column):
    # Convertir la lista de palabras clave a eliminar a minúsculas
    palabras_clave_a_eliminar_lower = [palabra.lower() for palabra in palabras_clave_a_eliminar]
    
    def process_cell(cell):
        # Si la celda es una cadena, la dividimos en una lista usando el separador ';'
        if isinstance(cell, str):
            terminos = [termino.strip() for termino in cell.split(';') if termino.strip()]
        # Si ya es una lista, la usamos directamente
        elif isinstance(cell, list):
            terminos = [str(termino).strip() for termino in cell if str(termino).strip()]
        else:
            terminos = []
        # Filtrar los términos que, al pasar a minúsculas, estén en la lista a eliminar
        terminos_filtrados = [termino for termino in terminos if termino.lower() not in palabras_clave_a_eliminar_lower]
        # Unir la lista filtrada en una cadena usando '; ' como separador
        return '; '.join(terminos_filtrados)

    return column.apply(process_cell)

# Aplicar la función a las columnas "Index Keywords" y "Author Keywords"
df['Index Keywords'] = eliminar_palabras_clave(df['Index Keywords'])
#df['bothKeywords'] =  eliminar_palabras_clave(df['bothKeywords'])
df['Author Keywords'] = eliminar_palabras_clave(df['Author Keywords'])
# Guardar el DataFrame filtrado en un nuevo archivo CSV

# Construir listado global normalizado
all_terms = pd.concat([
    df['Index Keywords'].dropna(),
    df['Author Keywords'].dropna()
]).str.split(';').explode().str.strip()

# Frecuencia sobre versión normalizada
freq = all_terms.str.lower().value_counts()
keep_norm = set(freq[freq > 1].index)

def filter_unique(cell):
    if not isinstance(cell, str):
        return ""
    terms = [t.strip() for t in cell.split(';') if t.strip()]
    filtered = [t for t in terms if t.lower() in keep_norm]
    return '; '.join(filtered)

df['Index Keywords'] = df['Index Keywords'].apply(filter_unique)
df['Author Keywords'] = df['Author Keywords'].apply(filter_unique)
# Guardar el DataFrame filtrado en un nuevo archivo CSV
#df.to_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv", index=False)

df.to_csv("G:\\Mi unidad\\2024\\Msc. Alberto León Batallas\\nuevoarticulo\\artículo final\\data\\datawos_scopuseliminadas.csv", index=False)
print("Palabras clave específicas eliminadas y nuevo archivo guardado.")
