import pandas as pd

# Cargar el archivo CSV
#df = pd.read_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv")

df = pd.read_csv(r"G:\\Mi unidad\\2025\\Master Italo Palacios\\articulo\\wos_scopus_reemplazado.csv")
   # Lista de palabras clave a eliminar (en minúsculas)
palabras_clave_a_eliminar = [

   "article", "priority journal", "procedure", "nonhuman", "animal", "control study",
    "greenpeace", "be", "eurasia", "adult", "male", "female", "child", "young adult",
    "student", "school", "university sector", "bible metric analysis", "human experiment",
    "infrastructure", "software", "chemistry", "commerce", "common", "physiology",
    "metabolism", "mortality", "japan", "california", "pennsylvania", "philadelphia",
    "vietnam", "malaysia", "mexico north america", "pakistan", "nigeria", "iran",
    "thailand", "victoria australia", "west africa", "south korea", "united kingdom",
    "canada", "australia", "north america", "latin america", "europe", "eurasia", "world",
    "city", "neighbourhood", "housing", "market", "business", "commerce", "funding",
    "profitability", "cost", "cost effectiveness", "certification", "law and legislation",
    "legislation and jurisprudence", "policy making", "politics", "politic",
    "government regulation", "regulatory framework", "regulatory approach",
    "management practice", "organization and management", "organization", "manager",
    "public sector", "private sector", "private land", "property right",
    "qualitative analysis", "quantitative analysis", "survey", "questionnaire",
    "questionnaire survey", "data collection", "data set", "database", "search engine",
    "software", "model", "model theoretical", "numerical model", "machine learning",
    "decision support system", "decision support tool", "remote sensing technology",
    "satellite imagery", "life cycle assessment", "bibliographic/bibliometry terms",
    "literature review", "review", "science", "scientific literature", "scientist",
    "academic research", "academic performance", "academic program", "teaching",
    "curriculum", "curriculum", "lesson", "high education", "education", "psychology",
    "sociology", "social responsibility", "social inclusion", "social movement",
    "social change", "well being", "health", "health hazard", "health risk",
    "public health", "environmental health", "epidemiology", "epidemic", "disease",
    "disease control", "disease spread", "mortality", "adolescence/adult/aged",
    "air pollution control", "wastewater", "wastewater treatment",
    "waste water management", "waste water recycling", "waste management",
    "solid waste management", "drinking water", "potable water", "water pollution",
    "urban heat island", "microclimate", "temperature", "atmospheric pollution",
    "atmospheric temperature", "greenhouse effect", "greenhouse gas emission",
    "emission", "emission control", "gas emission", "methane", "nitrogen", "phosphorus",
    "fertilizer", "fertilizer application", "soil pollutant", "soil pollution",
    "contamination", "contaminated land", "contaminated site", "bioremediation",
    "biodegradation", "adsorption", "eutrophication", "phytoremediation",
    "biotechnology", "biofuel", "bioenergy", "bioindicator", "biocatalyst",
    "enzymatic terms", "polymer", "catalysis", "catalyst", "charcoal", "carbonization",
    "carbon capture and storage", "direct air capture", "clean development mechanism",
    "energy", "energy efficiency", "energy conservation", "energy consumption",
    "energy resource", "electricity", "hydropower", "geothermal energy",
    "traffic and transport", "tourism", "recreational park", "recreational activity",
    "garden", "gardening", "park", "park recreational", "urban green space",
    "urban tree canopy", "canopy architecture", "physiology", "morphology", "seed",
    "seedling", "sapling", "poaceae", "shrub", "exotic specie", "evergreen tree",
    "deciduous tree", "fishery", "fish", "wildlife", "bird", "fauna", "biodiversity",
    "marine/coastal terms", "wetland", "desert", "arid region", "eastern hemisphere",
    "himalayas", "atlantic forest", "amazonia", "iran", "bangladesh", "cambodia",
    "croatia", "costa rich", "chittagong bangladesh", "chittagong hill tract",
    "ghana", "ireland", "indiana", "jiangsu", "melbourne", "victoria australia",
    "mexico", "pennsylvania", "philadelphia", "japan", "korea", "tanzania", "thailand",
    "pakistan", "nigeria", "vietnam", "south africa", "west africa", "east africa",
    "sub saharan africa", "urban agriculture", "agriculture worker",
    "fishery management", "food industry", "food supply", "food security", "livestock",
    "cattle", "palm oil", "bamboo", "eucalyptus", "palm oil", "poaceae", "cocoa",
    "coffee", "charcoal", "timber harvesting", "logging forestry", "logging",
    "forestry production", "plantation forestry", "forest product", "wood",
    "wood product", "building material", "construction", "brownfield",
    "brownfield site", "urban growth", "compact city", "city planning",
    "urban governance", "urban environment", "urban ecosystem", "urban greening",
    "urban green infrastructure", "urban tree", "street tree",
    "urban forest management", "urbanization", "building", "building material",
    "campus", "green campus", "campus sustainability", "university sector", "student",
    "research institution", "museum", "park recreational", "recreation",
    "recreation activity", "daily leisure", "dancing", "sports etc",
    "health care access", "health disparity", "health equity", "health impact",
    "health policy", "heart", "heavy metal", "heterogeneity", "high school student",
    "highland", "historical ecology", "human capital", "human health", "human impact",
    "iceland", "image reconstruction", "immobilization", "indicator indicator",
    "indicator instrument", "industrial economic", "industrial research",
    "information dissemination", "information management", "infrastructural development",
    "institutional timberland ownership", "intercropping", "invasive specie",
    "inventory control", "invertebrate", "irrigation system", "italia", "justice",
    "karnataka", "kenya", "kinetic", "land surface", "landfill", "landscape perception",
    "landscaping", "law enforcement", "lead", "leadership", "less sunda island",
    "level", "lignin", "lipase", "loess plateau", "magnetism", "malaria", "malawi",
    "mass media", "medicinal plant", "metal analysis", "metal nanoparticle",
    "metal organic framework", "meteorology", "middle east", "migration", "mining",
    "model validation", "morocco", "municipal solid waste", "museum", "nanoparticle",
    "narrative", "nitrate", "nongovernmental organization", "nonprofit organization",
    "north africa", "nutrient dynamic", "optical radar", "orchard", "organic compound",
    "organic pollutant", "organometallic", "overgrazing", "overstock", "ozone depletion",
    "pacific ocean", "para brazil", "particulate emission", "pastoralism", "pastoralist",
    "pasture", "pathology", "pattern", "per urban area", "performance",
    "performance assessment", "pharmaceutic", "philippine", "photocatalysis",
    "physical chemistry", "physical phenomenon", "physician", "physiological model",
    "physiological stress", "pica", "picea mariana", "poland", "policy instrument",
    "population distribution", "population dynamic", "population group",
    "population structure", "populous", "potassium", "prediction", "predictor variable",
    "primary education", "primary prevention", "primate", "privatization", "provenance",
    "province", "public good", "public space", "publication", "query", "radiation dose",
    "radiative forcing", "random forest", "rating", "recreational activity",
    "redevelopment", "representation", "residential location", "risk perception",
    "rubber", "rural society", "russian federation", "saline soil", "salinity",
    "sampling", "savanna", "seaweed", "sediment yield", "seed dispersal",
    "semiarid climate", "sign", "slovakia", "social behavior", "social class",
    "social justice", "social planning", "society", "socioeconomic condition",
    "soil type", "south and central america", "southeast asia", "spatial data",
    "specie difference", "state", "statistic", "statistic and numerical data",
    "structural equation modeling", "structured questionnaire", "subsidy system",
    "suburban area", "surface temperature", "survival", "survival rate",
    "sustainable campus", "sustainable city", "switzerland", "teacher education",
    "teacher training", "technology transfer", "temperature effect",
    "theoretical model", "theoretical study", "thermal comfort", "tillage",
    "timberland investment management organization", "time factor", "topography",
    "toxicity", "triacylglycerol lipase", "turkey", "uganda", "ukraine",
    "unclassified drug", "understory", "unsustainable development goal",
    "upland region", "urban agriculture", "urban design", "urban economy",
    "urban green area", "urban greenery", "urban sprawl", "uruguay", "variability",
    "vegetation structure", "vegetation type", "venezuela", "vertical",
    "vocational education", "volunteer", "washington united states", "waste treatment",
    "wastewater reclamation", "water contamination", "water flow", "water pollutant",
    "water stress", "water treatment", "water use", "water yield", "we",
    "western europe", "wild animal", "wildfire", "willow", "wind erosion",
    "wind velocity", "woody biomass", "youth", "yunnan", "zealand", "zero carbon",
    "zoophilia", "abatement cost", "abatement technology", "abiotic", "abiotic stress",
    "abnormal", "aboveground biomass", "abrupt change", "academic sector", "acadia",
    "acadia national park", "acceleration", "access", "access and benefit sharing",
    "access to finance", "accountability", "accra", "accreditation", "accumulation",
    "accuracy", "accuracy assessment", "accuse", "action situation", "activate sludge",
    "active zone", "activity of enzyme", "actor", "adaptability", "adaptive radiation",
    "additionally", "adjustment program", "administration", "administrative funding",
    "adsorbent", "adsorption kinetic", "advection", "advection fog", "advisory committee",
    "aerial", "aerial photography", "affordable housing", "afforestation standard",
    "after treatment", "agar", "age determination", "age distribution",
    "agent based model", "agglomeration", "agricultural chemical", "agricultural waste",
    "air drying", "air humidity", "air monitoring", "air pollutant removal",
    "air temperature", "albania", "albedo change", "allergen", "alternate land use",
    "alternative fuel vehicle", "altruism", "amazon basin", "ammonium derivative",
    "amylase", "anaerobic digestion", "analytic hierarchy process",
    "analytical framework", "ancient world", "anger", "animal food", "animal husbandry",
    "anthropogenic marine debris", "antibiotic agent", "aquaculture", "aquatic ecology",
    "aquatic ecosystem", "aquifer", "arable farming", "arcade", "archetype analysis",
    "architectural design", "archive", "argentina", "arid urban greenery", "army",
    "artificial intelligence", "artificial neural network", "ash dieback", "ashanti",
    "assembly rule", "assessment indicator system", "asset collateral",
    "assist migration", "asthma", "atlantic ocean", "atmosphere",
    "atmospheric chemistry", "atmospheric correction", "atmospheric radiation",
    "attitude change", "attitude to health", "auger hole planting technique", "author",
    "authority", "autocorrelation", "auxin", "avenue tree specie", "avian success",
    "awareness adoption matrix", "awash", "bacteria", "bacterial genome",
    "bacterial typing technique", "bacterium identification", "baltic state",
    "baltimore", "bamboo specie", "bangalore", "bangkok metropolitan region", "bare land",
    "bark beetle", "barrier to pro-environmental behavior", "basal area growth",
    "base composition", "baseline condition", "basic science", "basin management",
    "bathing beach", "bayesian network", "beach", "beach litter", "beach survey",
    "beech fir forest", "behavioural economic", "bendflow", "beneficiary",
    "benefit and problem", "benefit and value", "benelux", "benthic macroinvertebrate",
    "benzenedicarboxylate", "beta", "bibliographic database", "biblioshiny",
    "big data base water resource management", "bilateral cooperation",
    "bingham tibet plateau", "bio char", "bio latrines", "biochemical parameter",
    "biodegradable polymer", "biodiversity education", "biodiversity finance",
    "biodiversity institution", "biofertilizer", "biofortification", "biogas",
    "biogenic carbon", "biological control", "biological factor", "biological model",
    "biological monitoring", "biological parameter", "biological productivity",
    "biological resource", "biological water treatment", "biomass conversion factor",
    "biomass distribution", "biomass model", "biomass production", "biomethane",
    "biomonitoring", "biophysicochemical", "bioreactor", "biorefinery", "bioretention",
    "biosphere", "biotechnological approach", "biotechnological research",
    "biotransformation", "black spruce", "blending", "blood pressure", "bloomington",
    "bogor", "border", "bordering river", "botanic garden", "botanical survey",
    "botany teaching", "bound random walk", "bound rationality", "brain imaging",
    "breakdown", "breeding method", "breeding strategy", "broad application",
    "bronze age", "bubble", "buffalo", "buffer strip", "build environment",
    "building renovation", "bulk density", "bundle pe", "business analysis",
    "business as usual", "business entity", "business model", "business security",
    "business strategy", "bylaw", "cadmium", "calcareous soil", "calibration",
    "cameroon", "campeche", "campus sidewalk", "candidate", "canopy cover goal",
    "canopy density model", "canopy opening", "canopy tourism", "capacity gap",
    "capacity need", "capital efficiency", "capital intensity", "capital investment",
    "capsicum annuum", "car", "carbohydrate", "carbon accounting", "carbon budget",
    "carbon capture and utilization", "carbon compound", "carbon credit",
    "carbon emission accounting", "carbon leakage", "carbon neutral building",
    "carbon neutrality strategy", "carbon offset", "carbon offsetting",
    "carbon polygon", "carbon pool", "carbon reduction", "carbon reservoir",
    "carbon source", "carbon stocking", "carbon trading mechanism", "carbonic acid",
    "carboxylation", "cardamom", "caribbean", "carpathian", "catalyst activity",
    "catastrophic damage", "catering service", "cause effect relationship", "census",
    "certify emission reduction", "cetacean", "chaco", "chandigarh", "changchun",
    "chaotic state", "char", "charity", "charm", "chemical", "chemical analysis",
    "chemosynthesis", "cheonggyecheon", "chi square test", "chico",
    "child blood lead testing", "childcare", "childhood cancer",
    "childhood lead poisoning prevention act", "chitosan", "chlorination",
    "chlorophyll fluorescence", "chlorpyrifos", "choice and recognition",
    "chondrichthye", "cigarette butts", "cinnamomum camphora", "circular city",
    "citation analysis", "citizen consultation", "citizenship", "city garden",
    "city model", "city planning history", "city sustainability", "city tree",
    "civic engagement", "civil society", "civil war", "classification accuracy",
    "classification framework", "clean air act", "clean energy", "clean environment",
    "climate action planning", "climate change and leakage",
    "climate compatible development", "climate finance", "climate impact",
    "climate project", "climate smart agriculture", "climate smart forestry",
    "climate stress", "climate variability", "climber cutting",
    "clock and data recovery circuit", "cloud", "cloud computing environment", "club",
    "cluster analysis", "co benefit", "co management", "co occurrence analysis",
    "coal industry", "coal mining", "coal storage", "coastal habitat",
    "coastal zone management", "coastal zone problem", "cobalt", "cocoa",
    "cognitive hierarchy theory", "collaborative action", "collaborative governance",
    "collaborative partnership", "collaborative planning", "collapse transition",
    "collect earth", "collector efficiency", "college", "college building",
    "college student", "colloid", "colombia", "colonial legacy", "colonialism",
    "colorado river", "combustion exhaust", "command and control",
    "commercial activity", "commercial farming", "commodity price",
    "common agricultural policy", "common garden", "common land",
    "common pool resource", "communicable disease", "community academic partnership",
    "community assessment", "community base approach", "community base management",
    "community base natural resource management",
    "community base participatory research", "community base rehabilitation",
    "community characteristic", "community heterogeneity",
    "community institutional relation", "community lead stewardship",
    "community livelihood", "community of practice", "community organization",
    "community perception", "community project", "community resilience",
    "community science", "community service activity", "community water association",
    "comparative analysis", "comparative genomic hybridization", "compensation fund",
    "compensation system", "competitiveness", "compile", "complex interaction",
    "complex network", "composition of plant", "compost",
    "comprehensive environmental response compensation liability act",
    "comprehensive monitoring", "computational fluid dynamic", "computer program",
    "concentration composition", "conceptual knowledge", "condition assessment",
    "conductance", "conference of party", "connection", "connective practice",
    "conference proceeding", "conservatory management", "constellation analysis",
    "consumption rate", "contaminant of emerging concern", "contaminated site management",
    "contaminated site remediation", "control drug delivery", "control system",
    "conventional energy source", "cooking", "cool material", "cooling",
    "cooling effect", "coordination reaction", "copenhagen", "coral",
    "coral gardening", "coral micro fragmentation", "coral reef", "corolla",
    "correctional facility", "correctional institution", "correlation coefficient",
    "cost engineering", "cote do voice", "cotton", "covid 19", "credibility", "crime",
    "crisis intervention", "cryosphere", "crystalline material", "crystalline order",
    "cuba", "cultural institution", "curricular integration", "cyanobacteria", "cyclone",
    "cytology", "dairy", "dairy cattle", "dancing", "dangerous good", "dengue",
    "deep sea", "deep sea ecosystem", "deep sea organism", "deep sea sediment",
    "dehydration", "decommissioning", "decommissioning nuclear reactor",
    "dielectric/diffusion", "digital technology", "direct current", "direct evolution",
    "disadvantaged asthma", "disease", "disease surveillance", "disease transmission",
    "disruptive endocrine chemical", "dissolution", "distant future",
    "distributed database system", "domestic space", "douglas fir", "droplet",
    "drug delivery system", "drug formulation", "dry gel conversion",
    "dry stigma yield", "dublin descriptor", "dune", "dye", "dylan", "ebay", "ebb",
    "eco shopping", "eco social violence", "ecological engineering definition",
    "ecological trot", "educational video", "elastomer", "electrochemical analysis",
    "electrochemical technique", "electroencephalogram", "electroencephalography",
    "electrolyte", "electroremediation", "elephant", "elvis", "elwood", "embryophyta",
    "emergency", "emerging infectious disease", "empiricism", "employee",
    "end of life benefit", "endocrine disruptor", "enzymatic modification",
    "enzyme immobilization", "enzyme stability", "epidemic control", "ergonomic",
    "error analysis", "esterification", "estuary", "ethnic group",
    "ethnographic fieldwork analysis", "ETSAP TIAM", "EU", "evaluation index system",
    "evaluation indicator", "evaporation", "event related potential",
    "evoked response", "exotic plantation", "export", "eye movement", "eyelid reflex",
    "fabaceae", "falcon", "feather", "fee", "feedstock", "field method",
    "financial data processing", "fireproofing", "fish population", "fishery policy",
    "fishery regulation", "fishing down the food web", "flagstaff", "floating wetland",
    "flood bypass", "flood defence", "food preference", "food safety", "food storage",
    "food supplementation", "forest didactic path", "forest park",
    "formal concept analysis", "fossil fuel energy", "frankfurt be main",
    "frequency analysis", "frozen soil", "fuel efficient stove", "fungal genome",
    "fungus isolation", "future application", "fuzzy mathematic", "gene expression",
    "gene sequence", "genetic engineering", "genome analysis", "genomic DNA",
    "gentrification", "geodetic satellite", "geographic & geological phenomenon",
    "gluten", "good investment", "graduate student", "grapheme", "graphitic carbon nitride",
    "grid extension", "ground resolution", "gym", "gypsy moth", "health care access",
    "health disparity", "health equity", "health impact", "health policy", "heart",
    "heat thermal stress", "heavy metal", "height increment", "herbarium specimen",
    "hermeneutic", "heterogeneous catalyst", "hexapod", "hide", "hierarchical system",
    "high school student", "high quality wetland development", "hindu kush",
    "historical reference system", "honda shikoku", "household energy", "housewife",
    "human herpes virus", "hydraulic simulation testing", "hydrodynamic",
    "hydrogen evolution", "hydrogen sulfite", "hydrothermal synthesis",
    "hyperaccumulator plant", "hypothesis testing", "iceland",
    "identification control system", "image enhancement", "image processing",
    "image resolution", "immaterial", "immigration", "immunoglobulin", "imperialism",
    "impervious surface area", "import", "importance sampling", "in building",
    "in depth interview", "independent learning", "indianapolis", "industrial research",
    "information management", "infrastructural development",
    "karnataka/kenya/malawi/maryland/morocco/netherland/new zealand/poland/slovakia/switzerland/tunisia/uganda/ukraine/uruguay/venezuela/washington united states/yunnan/zealand",
    "magnetism", "malaria", "mass media", "mathematical model", "metal analysis",
    "metal nanoparticle", "metal organic framework", "meteorology",
    "metropolitan area", "mining", "model validation", "museum", "nanoparticle",
    "narrative", "nitrate", "optical radar", "organometallic", "overstock", "ownership",
    "ozone depletion", "pacific ocean", "particulate emission", "pathology",
    "performance assessment", "pharmaceutic", "photocatalysis", "physical chemistry",
    "physician", "physiological model", "pica", "pilot project",
    "place based education", "poland central europe", "potassium",
    "prediction/predictor variable", "primary education/primary school", "primate",
    "privatization", "process", "program evaluation", "project", "provenance",
    "public space", "publication", "quality", "query", "radiation dose",
    "radiative forcing", "rainfall", "rating", "recreation/recreational activity",
    "regulatory approach", "representation", "research field/frontier/method",
    "residential location", "resource", "responsibility", "risk perception",
    "saline soil/salinity", "satellite", "seaweed", "sediment yield", "sign", "Slovakia",
    "social class", "social planning", "specie difference", "state", "statistic",
    "structural equation modeling", "structured questionnaire", "subsidy system",
    "suburban area", "surface temperature", "sustainability indicator",
    "sustainable campus", "teacher education/training", "technology transfer",
    "theoretical model/study", "thermal comfort",
    "timberland investment management organization", "time factor", "topography",
    "toxicity", "triacylglycerol lipase", "triple bottom line", "trust",
    "unclassified drug", "united nations", "unsustainable development goal",
    "urban design/economy/greenery", "vertical", "vocational education", "volunteer",
    "waste treatment", "wastewater reclamation", "water contamination",
    "water treatment", "we", "wild animal", "willow", "wind velocity", "youth",
    "health care access", "health disparity", "health equity", "health impact",
    "health policy", "heart", "infection risk", "inner city asthma", "inner ear",
    "info world congress", "inform consent", "industrial area", "industrial development",
    "industrial ecology", "industrial emission", "industrial enterprise",
    "industrial sector", "industry", "infield outland", "immobilization",
    "indicator indicator", "indicator instrument", "information and communication technology",
    "information and technology", "information center", "information retrieval",
    "information support", "information technology", "insurance", "insula", "intercity",
    "interface", "internal characteristic", "internationality", "internet",
    "internet search engine", "interpersonal communication", "interview as topic",
    "into burma hotshot", "introduction", "invention", "iron", "iron nanoparticle",
    "irving gabon sis", "islamic value", "it", "italy", "jackie broker", "jesus edward",
    "jujube", "june drop baird", "juniper pro era", "juvenile", "kalmia",
    "kalmia augustifolia", "kanchenjunga", "kassel", "kentucky", "kenya senegal sis",
    "key management", "kharkiv", "kiln drying", "know enamel condensation",
    "knowing doing", "koala bumper west malaysia", "koel reuters panic late", "la",
    "lactase", "lager media floribunda", "lago nigeria", "lago state", "lake bosom we",
    "lake boss twi", "lake harass", "lake way", "lake whitefish", "lead in water",
    "lead paint", "lead poisoning", "lead poisoning prevention education",
    "lead prevention policy", "life cycle stage", "literacy", "literature",
    "literature map", "literature study", "lithuania", "living community",
    "living environment", "living infrastructure", "living laboratory", "locking",
    "log durability", "logging company", "logistic regression", "london", "low cost cd",
    "low income asthma", "low molecular weight", "low saxony", "loyang lake",
    "lubrication", "lucknow", "lulu", "lunch program", "lyceum", "lyceum barb rum",
    "lyme disease", "macroalgae", "magnetic", "magnetic biocatalyst",
    "magnetic nanoparticle", "magnetic phenomenon", "malnutrition", "malta",
    "malvaceae", "management collection", "management cost", "management issue",
    "management mode", "management model", "management science", "management solution",
    "mandate collaboration", "manganese", "manganese mine", "manganese ore",
    "manitou", "manure", "maratha", "marine agronomy", "marine debris",
    "marine education", "marine environment", "marine pollution", "market condition",
    "market system", "marketing", "mashhad", "mass balance", "massachusetts",
    "matadi", "mathematical analysis", "matthiola", "maximum likelihood",
    "mazowieckie", "meadow", "media", "medical application", "medical education",
    "medical information", "medical research", "medicine", "memory", "mental capacity",
    "mental model", "mental stress", "mercury", "merger and acquisition",
    "metabolic network and pathway", "metal cutting", "metal element", "metal heavy",
    "metal ion", "metal oxide", "metal recovery", "meteorological phenomenon",
    "metropolitan", "mexico city", "miami date county", "michoacan", "microalga",
    "microbe assist green technology", "microbial community", "microbial degradation",
    "microbial diversity", "microbiology", "microcosm", "microwave synthesis",
    "mid atlantic region", "mid latitude environment", "middle aged", "midland",
    "midwestern united state", "military engineering", "military government",
    "military operation", "militia excel", "milk", "millennium development goal",
    "mine", "mine spoil", "mine spoil dump restoration", "minnesota", "minority group",
    "miscellaneous name group", "missouri basin", "mobilization", "mode science",
    "model biological", "model of corporate", "modelling tool", "moderating role",
    "modification", "molecular weight", "mongolian", "montgomery county",
    "montgomery county maryland", "morbidity", "morceau", "morph",
    "morphology analysis", "moss", "moss bio indicator", "mowing", "multidimensionality",
    "multiple party", "multiple stakeholder", "multipurpose", "multipurpose specie",
    "myanmar", "nan porous material", "nanjing ring", "nanomagnetic", "narayani",
    "national institute of environmental health sciences we",
    "nationally carbon conversion", "natural enemy", "natural history",
    "naturalistic setting", "near cognitive measure", "need",
    "neighbourhood electric vehicle nev", "nematode abundance", "net benefit",
    "net zero energy", "neuroimaging", "neuron", "neutralization", "new brunswick",
    "new england", "new mongol", "newfoundland", "newfoundland and labrador",
    "next generation network", "nickel", "niger delta", "niger nigeria",
    "no point source pollution", "noise pollution", "non formal space", "non paved",
    "non structural measure", "nondestructive examination", "norm", "normal",
    "normal human", "north shawn", "northeast", "northern region thailand",
    "northwest highland of ethiopia", "novel ecosystem", "nuclear accident",
    "nuclear disaster", "nucleation", "nucleic acid hybridization", "nucleotide",
    "numerical method", "nursery ground", "oasis", "occupation", "ocean health",
    "ocean solution", "ocean surface", "oceanography", "oct flag munich we",
    "oil and fat", "oil spill", "oil well flooding", "okra", "old growth forest",
    "oligomer", "olive oil production", "oman", "online monitoring",
    "online platform", "online tracking", "ontology", "open access", "open source",
    "operation research", "opitutaceae", "option to harvest", "or code", "orbit", "ore",
    "organ oil", "organic chemical", "organic coffee", "organizational characteristic",
    "orientation", "ornament", "out migration", "outdoor environment",
    "outdoor learning", "outdoor microclimate", "overall accuracy", "overburden",
    "oxidation kinetic", "oxidative stress", "pacific coast chile", "pair",
    "pair watershed", "pairwise ranking", "panel econometric", "paradigm shift",
    "parcel", "parcel level", "parcel structure", "parent", "parkinson acute to",
    "patient education", "patient monitoring", "pedestrian",
    "pedestrian thermal comfort", "per capita", "performance optimization",
    "peripheral region", "peroxidase", "persia kurtis", "persistent organic pollutant pop",
    "personal care", "personal care product", "personal experience",
    "pharmaceutical care", "phenotypic plasticity", "photo thermal therapy",
    "photodegradation", "photography", "photovoice", "phytosociology", "pica abies",
    "pica ruben", "pin…", "pitfall", "place base", "planctomycetota",
    "planning history", "plant extract", "plant health care", "plant leaf",
    "plant leave", "plant parameter", "plastic", "play", "plot level data", "plutonium",
    "point cloud modeling", "policy culture", "policy cycle", "policy goal",
    "political history", "political ontology", "political participation",
    "political partisanship", "poly chlorinate biphenyl / PCB", "portable electronic",
    "portfolio", "portland", "positive experience", "post accident operation",
    "power market", "power plant", "poznan", "practical morality", "practitioner",
    "precipitation intensity", "precision planning", "preservation", "pretoria",
    "price elasticity of supply", "print circuit board", "prison", "prisoner",
    "probability", "process tracing", "procurement", "product design",
    "production rate", "productive chain", "professional competence",
    "professionalism", "profit model", "prognosis",
     "emotion",
 "tracy glycerol lipase", "asia","future",
 "experience","agreement","brazil",
"india",
"nepal",
"ecuador",
"chile", 	"china", "conflict", "agency","united states","human",

]

# Función para eliminar palabras clave específicas y retornar una cadena
def eliminar_palabras_clave(column):
    # Convertir la lista de palabras clave a eliminar a minúsculas
    palabras_clave_a_eliminar_lower = [palabra.lower() for palabra in palabras_clave_a_eliminar]
    
    def process_cell(cell):
        # Si la celda es una cadena, la dividimos en una lista usando el separador ';'
        if isinstance(cell, str):
            terminos = [termino.strip() for termino in cell.split(';') if termino.strip()]
        # Si ya es una lista, la usamos directamente
        elif isinstance(cell, list):
            terminos = [str(termino).strip() for termino in cell if str(termino).strip()]
        else:
            terminos = []
        # Filtrar los términos que, al pasar a minúsculas, estén en la lista a eliminar
        terminos_filtrados = [termino for termino in terminos if termino.lower() not in palabras_clave_a_eliminar_lower]
        # Unir la lista filtrada en una cadena usando '; ' como separador
        return '; '.join(terminos_filtrados)

    return column.apply(process_cell)

# Aplicar la función a las columnas "Index Keywords" y "Author Keywords"
df['Index Keywords'] = eliminar_palabras_clave(df['Index Keywords'])
#df['bothKeywords'] =  eliminar_palabras_clave(df['bothKeywords'])
df['Author Keywords'] = eliminar_palabras_clave(df['Author Keywords'])
# Guardar el DataFrame filtrado en un nuevo archivo CSV

# Construir listado global normalizado
all_terms = pd.concat([
    df['Index Keywords'].dropna(),
    df['Author Keywords'].dropna()
]).str.split(';').explode().str.strip()

# Frecuencia sobre versión normalizada
freq = all_terms.str.lower().value_counts()
keep_norm = set(freq[freq > 1].index)

def filter_unique(cell):
    if not isinstance(cell, str):
        return ""
    terms = [t.strip() for t in cell.split(';') if t.strip()]
    filtered = [t for t in terms if t.lower() in keep_norm]
    return '; '.join(filtered)

#df['Index Keywords'] = df['Index Keywords'].apply(filter_unique)
#df['Author Keywords'] = df['Author Keywords'].apply(filter_unique)
# Guardar el DataFrame filtrado en un nuevo archivo CSV
#df.to_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv", index=False)

df.to_csv(r"G:\\Mi unidad\\2025\\Master Italo Palacios\\articulo\\datawos_scopuseliminadas.csv", index=False)
print("Palabras clave específicas eliminadas y nuevo archivo guardado.")
