import pandas as pd

# Cargar el archivo CSV
#df = pd.read_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv")

KW_COLS     = ["Author Keywords", "Index Keywords"]

df = pd.read_csv(r"G:\Mi unidad\2025\Master  FRANCISCO MARCELO ALVARADO PORRAS\data\datawos_scopusreplace.csv")
   # Lista de palabras clave a eliminar (en minúsculas)
palabras_clave_a_eliminar = [

    # salud / bio / generales
    "healing",
    "health-risk assessment",
    "health expenditure growth",
    "health risk",
    "healthcare",
    "heat",
    "heat pump",
    "heavily polluting enterprises",
    "heavy-metal distribution",
    "heavy pollution",
    "heavy pollution industry",
    "hedge",
    "help",
    "heritage tourism",
    "heterogeneity effect",
    "heterogeneous brokerage",
    "heterogeneous green innovation",
    "heterogeneous treatment effects",
    "hfcs",
    "hidden costs",
    "hierarchical interventions",
    "high-level expert panel",
    "high-mountain ecosystem",
    "high-quality economic development",
    "high-quality urban development",
    "high-speed rail",
    "high-standard farmland construction policy",
    "high temperature requirement",
    "higher ethanol-production",
    "highrise buildings",
    "himalaya",
    "himalayan region",
    "himalayas",
    "hipcs",
    "hispanic migration",
    "histology",
    "historical baselines",
    "historical data",
    "historical geography",
    "historical institutionalism",
    "historical materialism",
    "historical perspective",
    "historical trauma",
    "hmf",
    "hmong",
    "hog production",
    "holt model",
    "honey-bees",
    "horizon 2020",
    "horizon scan",
    "horizontal and vertical relationships",
    "host communities",
    "host development",
    "house of representatives",
    "household carbon emissions",
    "housing",
    "hr-mas nmr",
    "hugershoff",
    "human activities",
    "human activity",
    "human experiment",
    "human geography",
    "human population",
    "human response",
    "hybrid emission control",
    "hybrid knowledge",
    "hybrid management",
    "hybridization",
    "hydrazine",
    "hydrocarbon reservoir",
    "hydrocarbons",
    "hydroelectric power",
    "hydroelectricity",
    "hydrofluorocarbon",
    "hydrofluorochlorocarbons",
    "hydrogen",
    "hydrological future",
    "iberian peninsula",
    "ices",
    "identities",
    "ignorance",
    "ile de france",
    "imaginacion",
    "imagination",
    "imitation",
    "immunity",
    "impact factors",
    "impact mechanism",
    "impartial trust",
    "imperial mode",
    "implementation gap",
    "implementation success",
    "implied volatility",
    "import",
    "improved tapio decoupling principle",
    "improved water source",
    "improvements",
    "inbound tourism",
    "incidence",
    "inclusiveness",
    "income-distribution",
    "index funds",
    "index ndwi",
    "indexes",
    "indian ocean",
    "industrial-innovation",
    "industrial collaborative agglomeration",
    "industrial coordination",
    "industrial digitalization",
    "industrial diversification",
    "industrial eco-efficiency",
    "industrial economics",
    "industrial intensification",
    "industrial land transfer",
    "industrial organization",
    "industrial relocation",
    "industrial sector",
    "industrialization stage",
    "industries",
    "industries value added",
    "industry effects",
    "infant-mortality evidence",
    "infections",
    "inference",
    "influence",
    "infodemic",
    "information-seeking",
    "information asymmetry",
    "information credibility",
    "information processing",
    "information provision",
    "information spillovers",
    "information systems",
    "information use",
    "infrastructural development",
    "infrastructure development",
    "initial capital",
    "innovation ability",
    "innovation journeys",
    "innovation policy",
    "innovation quality",
    "innovations",
    "innovative city pilot policy",
    "inoculation",
    "input-output",
    "input -output linkages",
    "instability",
    "institution building",
    "institutional arrangement",
    "institutional capacities",
    "institutional dimensions",
    "institutional distance",
    "institutional economics",
    "institutional epistemology",
    "institutional overlap",
    "institutional pressure",
    "institutional resilience",
    "institutional trust",
    "institutional voids",
    "instrument choice",
    "instrumental variable",
    "instrumentation",
    "insurance",
    "integrated choice",
    "integrated management",
    "integrated thinking",
    "integrated pollution prevention",
    "interactive incorporation",
    "interagency",
    "intercomparison project",
    "interdisciplinary approach",
    "interdisciplinary integration",
    "interdisciplinary research project",
    "interest",
    "interest group",
    "interface",
    "interfaces",
    "interior design",
    "intermediary agents",
    "intermediation effect model",
    "intermodal terminals",
    "internal migration",
    "international-business",
    "international actor",
    "international aid",
    "international business theory",
    "international community",
    "international competition",
    "international conflict",
    "international economic system",
    "international forest",
    "international instrument",
    "international legal acts",
    "international norms",
    "international standards",
    "international technology diffusion",
    "international tourism",
    "international tourist arrivals",
    "international urbanization",
    "internationalization",
    "internet of things",
    "internet of things environmental applications",
    "interplay",
    "interprovincial ecological efficiency",
    "intersection",
    "interventions",
    "interviews",
    "intra-seasonal variations",
    "inuit art",
    "inventive activity",
    "inventory",
    "inverse response to climate",
    "investment eroi",
    "investment evidence",
    "investment history",
    "investor attention",
    "invisible hand",
    "ioe-wef",
    "iran",
    "iranian fundamental rules and regulations",
    "iron",
    "iron and steel enterprises",
    "irreversibility",
    "irrigation technologies",
    "irrigation water supply",
    "island imaginaries",
    "isotopes",
    "issue-attention",
    "itlos",
    "j61",
    "japanese firms",
    "jatropha",
    "jatropha-curcas",
    "jin-ji region",
    "job-satisfaction",
    "johannesburg",
    "johor",
    "joint emission reduction",
    "joint interplay management",
    "joint nationally determined contribution",
    "jordan river-basin",
    "journalism",
    "journalistic sourcing",
    "journals",
    "judicial practice",
    "jurisdictional approach",
    "jurisdictional redd+",
    "justice-based norms",
    "juventud",
    "k-means clustering",
    "kakadu national-park",
    "karl polanyi",
    "key enabling technologies",
    "key impact factors",
    "key performance indicator",
    "kiribati",
    "knowledge bases",
    "knowledge dynamics",
    "knowledge map",
    "knowledge mapping",
    "knowledge narrative",
    "knowledge networks",
    "knowledge production function",
    "knowledge resource",
    "knowledge spillovers",
    "knowledge status",
    "knowledge synthesis",
    "knowledge transfer",
    "knowledge translation",
    "labor",
    "labor markets",
    "labor mobility",
    "laboratory compacted",
    "lake mendota",
    "lake qinghai",
    "lake urmia",
    "land-cover",
    "land-surface",
    "land-surface phenology",
    "land-tenure",
    "land-use-land-cover",
    "land-use conflict",
    "land-use sector",
    "land acquisitions",
    "land administration",
    "land concessions",
    "land cover change",
    "land use management",
    "land use permitting",
    "land use variation",
    "landcare",
    "landsat 8",
    "landscape change",
    "landscape genetics",
    "landscape metrics",
    "landscape pattern",
    "large-scale",
    "large dams",
    "late industrialism",
    "latent class choice model",
    "latent dirichlet allocation",
    "latent environmental problems",
    "law-policymakers",
    "law-science nexus",
    "law of development",
    "leader– follower game",
    "leading official's accountability audit of natural resources",
    "leaf-area index",
    "leaf bud burst",
    "learning-based intervention",
    "learning landscape",
    "least squares method",
    "legal",
    "legal change",
    "legal culture",
    "legal/regulatory/public policy",
    "legalization",
    "lens",
    "liberalization",
    "life-cycle",
    "life-history parameters",
    "life cycle models",
    "life expectancy",
    "life programme",
    "life satisfaction",
    "light",
    "light use efficiency model",
    "lightgbm machine learning",
    "lignocellulosic biomass",
    "liminal",
    "limitation",
    "line 9",
    "linear programming",
    "linear time",
    "linkage",
    "linkages",
    "linking project",
    "linking science and policy",
    "lionfish",
    "liquid",
    "listed companies",
    "litigation dispute settlement",
    "litter",
    "litter decomposition",
    "livelihood trade-offs",
    "living-with",
    "living well/earth mother",
    "lizard peninsula",
    "lmdi",
    "lmdi decomposition",
    "loan spread",
    "local",
    "location",
    "logistics industry",
    "logit regression",
    "long-run",
    "long-term",
    "long-term change",
    "long-term sustainability",
    "loreto",
    "los angeles",
    "los angles",
    "losses",
    "lost",
    "lot-size",
    "low-carbon development index",
    "lstm",
    "lumbee",
    "m-and-a",
    "machine",
    "machine learning and text analysis",
    "machinery",
    "mackerel",
    "magazines",
    "mainstreaming",
    "major specialities analysis",
    "malacostraca",
    "malaysia",
    "male plumage",
    "malmquist-luenberger index",
    "malmquist luenberger index",
    "management-practices",
    "management-systems",
    "management decision",
    "management practices",
    "management standards",
    "mandates",
    "mandatory criteria",
    "mangrove",
    "manufacturers",
    "manufacturing-industries",
    "manufacturing firms",
    "manufacturing industry",
    "manure",
    "marginal ice-zone",
    "marginalization",
    "marijuana",
    "marine",
    "marine and freshwater mortality",
    "marine debris",
    "marine ecological environment",
    "marine economic circle",
    "marine ecosystems",
    "marine scientific research",
    "marine social science",
    "maritime safety",
    "maritime security",
    "maritime transportation",
    "markal",
    "market-based approaches",
    "market conditions",
    "market design",
    "market entry",
    "market multi-agent green supervision",
    "market power",
    "market system",
    "marketing-strategy",
    "marketization",
    "mass-loss",
    "mass-media",
    "master chronology",
    "material semiotics",
    "materialisms",
    "mathematical abstractions",
    "mathematical modeling",
    "mathematical programming with equilibrium",
    "matters",
    "maximum allowable concentration",
    "mayors",
    "mea",
    "meaning",
    "meanings",
    "measurement",
    "mechanical technology",
    "mechanisms",
    "mechanization",
    "media discourse",
    "media discourses",
    "media representations",
    "mediating effect analysis",
    "mediation effect",
    "mediterranean environment",
    "medium",
    "medway estuary",
    "megafauna",
    "meherrin",
    "mekong delta",
    "melbourne",
    "melt",
    "member states",
    "membership",
    "mena",
    "mercury (element)",
    "mercury (metal)",
    "mercury compounds",
    "merging crisis",
    "mesoamerica",
    "meta-analysis",
    "meta-frontier non-radial malmquist index",
    "metabolism",
    "metabolomics",
    "metageographies",
    "metal-industry",
    "metal contamination",
    "metal drawing",
    "metal pollution",
    "metal toxicity",
    "metallurgy",
    "metaphor",
    "meteorological influences",
    "methane",
    "method of moments quantile regression",
    "methodological challenges",
    "methods-qualitative",
    "methods-quantitative",
    "metrology",
    "metropolitan region",
    "mexico-city",
    "mexico energy reform",
    "mexico valley metropolitan area",
    "mgrw model",
    "miami-dade",
    "microcystis sp",
    "microplastics",
    "mid-yangtze river urban agglomeration",
    "migrants at sea",
    "migration determinant",
    "migrations",
    "mikania",
    "milestones",
    "militarization",
    "military application",
    "mineral policy",
    "mineral trap",
    "mineralization",
    "mini-publics",
    "minimum participation threshold",
    "minimum price",
    "mining activity",
    "mining conflict",
    "mining industry",
    "mineralization",
    "minority group",
        # energía: conceptos muy genéricos o poco útiles como keyword temática
    "energy-exchange",
    "energy-food nexus",
    "energy-intensive industries",
    "energy-intensive industry",
    "energy-return",
    "energy-rich regions",
    "energy constraints",
    "energy demand",
    "energy knowledge",
    "energy markets",
    "energy performance contract",
    "energy scenarios",
    "energy sector",
    "energy strategy",
    "energy technical efficiency",
    "energy utilization efficiency",

    # genérico / empresa / finanzas / métodos
    "engaged research",
    "engineers",
    "england",
    "enjoyment",
    "enrollment",
    "enterprise employment",
    "enterprise export",
    "enterprise location selection",
    "enterprise peer influence",
    "enterprise productivity",
    "enterprise technological progress",
    "enterprise transformation mechanism",
    "enterprises in high-polluting industries",
    "enterprises? energy efficiency",
    "entrepreneurial city",
    "entrepreneurial leadership",
    "entropy",
    "entropy weight method",
    "envelopment",
    "environmental",
    "environmental data",
    "environmental parameters",
    "environmental variables",
    "equipment investment",
    "equity issuance",
    "equity markets",
    "evaluation",
    "evaporation",
    "everyday",
    "examples",
    "executive-compensation",
    "executive compensation incentive",
    "exercise",
    "exergy performance",
    "exit",
    "expansion",
    "experimental space",
    "experimentalism",
    "experimentation",
    "experiments",
    "expert-influence",
    "expert cultures",
    "expert discourses",
    "expert organizations",
    "expert politics",
    "explain",
    "exploration",
    "expression",
    "extent",
    "fabrication",
    "facilitate",
    "facilities",
    "factor agglomeration",
    "factor complementarity effect",
    "factor energy efficiency",
    "factor input",
    "factor input of productivity process",
    "family firms",
    "fantasy",
    "farmer ability and willingness",
    "farmer identity",
    "farmer subjectivity",
    "farmers participation",
    "fatigue life",
    "fcm",
    "fdi inflows",
    "fear appeals",
    "feasibility study",
    "feasible generalized least squares",
    "feed-in",
    "female",
    "female ceo",
    "female directors",
    "field",
    "field-configuring events",
    "field experiment",
    "field work",
    "fieldwork",
    "financial-emission reduction policy",
    "financial disclosure",
    "financial efficiency",
    "financial inclusion",
    "financial innovation",
    "financial market",
    "financial mechanisms",
    "financial services",
    "financial structure",
    "financial support",
    "financial systems",
    "financing",
    "financing cost",
    "financing decision",
    "fintech",
    "firm-level competition",
    "firm-value",
    "firm effects",
    "firm emissions",
    "firm performance evidence",
    "firm self-regulation",
    "firm size",
    "forms",
    "formulation",
    "formulations",
    "foundation",
    "foundations",
    "frame",
    "framing theory",
    "fund",
    "funding paradigm",
    "future challenges",
    "future scenario development",
    "futurity",
    "gap",
    "garbage",
    "gas",
    "gdp distribution",
    "geographic coordinates",
    "geographical information",
    "geographical location",
    "georeferentiation",
    "gm-bp",
    "gmm model",
    "goal achievement",
    "governance attributes",
    "governance factors",
    "governance indicators",
    "governance instruments",
    "governance mechanisms",
    "governance network",
    "governance reform",
    "government attention",
    "government effectiveness",
    "government intervention",
    "government policies",
    "government pressure",
    "government regulation",
    "government supervision",
    "governmental interventions",
    "google-scholar",
    "goods",
    "goods exchange",
    "graph",
    "gravity",
    "grey forecast",
    "grey prediction gm (1",
    "group-size",
    "group models",
    "growth-factors",
    "growth-layer groups",
    "guide",
    "gut microflora",
    "habitat",
    "harm",
    "hazard risk",
    "hazardous substances",
    "haze pollution",
        "competitive balance",
    "complementarity",
    "complex adaptive systems",
    "complex dynamics",
    "complex network",
    "composite system synergy model",
    "compounds vocs",
    "computable general equilibrium model",
    "computational intelligence",
    "computational social science",
    "computer simulations",
    "concentration (composition)",
    "concentration (parameters)",
    "conceptions",
    "concrete mixtures",
    "condition",
    "conditional probability",
    "conferences",
    "configuration",
    "configuration of factors",
    "confucian culture",
    "congress",
    "conjuncture",
    "connections",
    "contexts",
    "constraints",
    "constraints (mpec)",
    "construction-oriented state",
    "construction costs",
    "construction project",
    "constructivism",
    "constructivist approach",
    "consultancy firms",
    "consultants",
    "consumer-behavior",
    "consumption -based carbon emissions",
    "contested discourses",
    "context-rich images",
    "context-specific governance",
    "contextual interaction theory",
    "contingent valuation",
    "contingent valuation method (cvm)",
    "continuous did model",
    "contract",
    "controls growth cessation",
    "controversies",
    "conversion",
    "cooperative strategy",
    "coordination contract",
    "copepod community",
    "corn",
    "corporate attributes",
    "corporate capital structure",
    "corporate carbon economy",
    "corporate culture",
    "corporate disclosure",
    "corporate diversification",
    "corporate financial performance",
    "corporate financial results",
    "corporate financialization",
    "corporate green investment",
    "corporate investment",
    "corporate legitimacy",
    "corporate management",
    "corporate performance",
    "corporate philanthropy",
    "corporate power",
    "corporate research and development",
    "corporate values",
    "corporation",
    "corporations",
    "corpus discourse analysis",
    "correction",
    "corrective taxes",
    "correlation analysis",
    "correspondence analysis",
    "cosmology",
    "cost compensation mechanism",
    "cost of equity capital",
    "costly signaling",
    "cotton",
    "council",
    "counterfactual analysis",
    "countermovement",
    "country effects",
    "coupled human-natural systems",
    "coupled infrastructure systems",
    "coupling coordination",
    "coupling coordination degree model (ccdm)",
    "coupling degree",
    "cpc-y02",
    "cpis unit root test",
    "crayfish",
    "credibility",
    "credit resource allocation",
    "crime",
    "criminalization",
    "crisis management",
    "criteria",
    "critical acid loads",
    "critical action intellectuals",
    "critical approaches",
    "critical digital studies",
    "critical discourse analysis",
    "critical futures studies",
    "critical infrastructure",
    "critical loads",
    "critical night length",
    "critical state and governance theory",
    "critical sustainability studies",
    "critical systems theory",
    "critical theory",
    "crop-rotation patterns",
    "crop genetic resources",
    "crop phenotype acquisition system",
    "crop production",
    "crops",
    "cross-border investments",
    "cross-border mergers and acquisitions",
    "cross-level",
    "cross-level linkages",
    "cross-scale implementation",
    "cross-section",
    "cross-sector partnerships",
    "cross-system interactions",
    "cross -border lending",
    "crowding out",
    "crude-oil",
    "crude-oil price",
    "crustacea",
    "crusts",
    "cryosphere",
    "cryptocurrency",
    "cs-ardl",
    "csos",
    "cuculidae",
    "cultivars",
    "cultivation",
    "cultural-heritage",
    "cultural climatology",
    "cultural heritage",
    "cultural landscapes",
    "cultural norms",
    "cultural politics",
    "cultural resources",
    "cultural theory",
    "cultural tradition",
    "cultural transmission",
    "cumulative effects",
    "curiosity driven research",
    "curtailment",
    "custom duty",
    "customary and state land",
    "cyano-habs",
    "cyanobacteria",
    "cyber-systemic",
    "cybersecurity",
    "d30",
    "dagum's gini coefficient",
    "daily industry",
    "dam safety",
    "dangerous goods",
    "dark earths",
    "data -driven rule -base",
    "data analytics",
    "data envelopment analysis",
    "data envelopment analysis (dea)",
    "data processing",
    "data triangulation",
    "database",
    "databases",
    "datafication",
    "day degrees",
    "dcce",
    "de-extinction",
    "dea-model",
    "dea-tobit",
    "dea environmental assessment",
    "dea model",
    "dead",
    "debate",
    "debris",
    "debt-evidence",
    "debt restructuring",
    "decapoda",
    "decision",
    "decision context",
    "decision support systems",
    "decision support tool",
    "decision to invest",
    "decisive spaces",
    "declaration",
    "declining species",
    "decomposable penalty method",
    "decoupling efforts",
    "decoupling relationship",
    "deep-learning framework",
    "deep biosphere",
    "deep learning",
    "deep sea",
    "default",
    "defaults",
    "defective production",
    "deficit irrigation",
    "definitions",
    "degazettement",
    "degree of agency",
    "delay",
    "delayed effect",
    "delegation",
    "delphi",
    "delphi assessment",
    "delta",
    "delta variant",
    "demand-pull",
    "dematerialization",
    "democratic systems",
    "denmark",
    "density",
    "density-dependence",
    "density stress",
    "dependence",
    "deposition",
    "desert dust",
    "development context",
    "development expenditures",
    "development finance",
    "development goals",
    "development paths",
    "development strategy",
    "developmental timing",
    "diameter variations",
    "diamond risk",
    "did model",
    "diesel-engine",
    "dieselgate",
    "diet",
    "difference-in-difference-in-differences",
    "difference-in-difference design",
    "difference-in-difference method",
    "difference-in-difference models",
    "difference-in-differences (did)",
    "difference-in-differences method",
    "difference -in -difference model",
    "difference -in -differences method",
    "difference -in -differences model",
    "difference in difference in difference",
    "difference in differences model",
    "differential expression",
    "digital cooperation",
    "digital image processing",
    "digital inclusion",
    "digital storytelling",
    "digital technology",
    "digital trade",
    "digitalisation",
    "dilemma",
    "dimensions",
    "dioxide",
    "dioxide capture",
    "direct potable reuse",
    "disaster & risk management",
    "disaster anthropology",
    "disaster management",
    "disaster mitigation",
    "disaster risk",
    "disaster risk-management",
    "disaster risk reduction",
    "disavowal",
    "discourse coalitions",
    "discursive hegemony",
    "disease",
    "displacement",
    "disposal",
    "disproportionate burden",
    "dispute settlements",
    "disruption",
    "distant-future",
    "distributional problems",
    "district",
    "district heating systems",
    "divide",
    "divided government",
    "divisia index",
    "doctrine",
    "domestic firms",
    "domestic research project",
    "domestic sources",
    "donors",
    "dormancy release",
    "double carbon",
    "double carbon goal",
    "double dividend",
    "double effect",
    "dpsr model",
    "drawbacks",
    "drawing",
    "drive",
    "driven",
    "drylands",
    "dsd",
    "dual carbon goals",
    "dual control of amount and intensity of energy consumption (dcec) policy",
    "dumping",
    "duopoly",
    "dust storm",
    "dutch farmers",
    "dynamic dependence",
    "dynamic effect",
    "dynamic evolution",
    "dynamic gmm models",
    "dynamic impact",
    "dynamic interaction effects",
    "dynamic material flow analysis",
    "dynamic mechanism design",
    "dynamic performance governance",
    "dynamic relationship",
    "dynamic threshold model",
    "dynamical systems",
    "e-government",
    "e-participation",
    "e7 countries",
    "early warning system",
    "earnings losses",
    "earth observation",
    "earth system",
    "earth system boundaries",
    "earth system justice",
    "earth system model",
    "earth system models",
    "earth system sciences",
    "earth systems",
    "earthquakes",
    "east-asia",
    "east-india-company",
    "east africa",
    "eastern boundary upwelling systems",
    "eastern seaboard cities",
    "eco-cities",
    "eco-community development",
    "eco-environment",
    "eco-environmental quality",
    "eco-homes",
    "eco-housing",
    "eco-innovation drivers",
    "eco-innovation index",
    "eco-political disability",
    "eco-state restructuring",
    "ecocene",
    "ecoimmunology",
    "ecolabel",
    "ecolabels",
    "ecological balance",
    "ecological behavior",
    "ecological character",
    "ecological democracy",
    "ecological emergency",
    "ecological holism",
    "ecological impacts",
    "ecological innovation",
    "ecological literacy",
    "ecological modernisation",
    "ecological native",
    "ecological norms",
    "ecological paradigm",
    "ecological resilience",
    "ecological sustainability",
    "ecological vulnerability",
    "ecologies",
    "econometric evaluation estimator",
    "econometric models",
    "economic-efficiency",
    "economic-geography",
    "economic-growth nexus",
    "economic-impacts",
    "economic-integration",
    "economic-performance",
    "economic-theory",
    "economic analysis",
    "economic and social effects",
    "economic aspects",
    "economic complexity",
    "economic instruments",
    "economic production",
    "economic regulation",
    "economic restructuring",
    "economic structures",
    "economic valuation",
    "ecosystem-based fisheries management",
    "ecosystem conservation",
    "ecosystem resilience",
    "ecosystem respiration",
    "ecosystem water use efficiency",
    "educational-attainment",
    "effective population-size",
    "effects of regional integration policies",
    "efficacy",
    "efficiency evidence",
    "efficiency measurement",
    "eia",
    "eight comprehensive economic zones",
    "eighteenth century",
    "el salvador",
    "elasticity",
    "elastomers",
    "election",
    "electric vehicle",
    "electric vehicles",
    "electricity industry",
    "electricity market liberalization",
    "electricity prices",
    "electricity production",
    "electricity regulation",
    "electrification",
    "electrochemical hydrogen storage",
    "element allocation efficiency",
    "embodied energy",
    "emergent policy fields",
    "emerging governance",
    "emerging powers",
    "emerging technologies",
    "emergy-based energy return on investment",
    "emergy intensity",
    "emergy synthesis",
    "emission-reduction",
    "emission cap",
    "emission inventory",
    "emission norms",
    "emission permits",
    "emission productivity",
    "emission reduction commitments",
    "emission reduction cost",
    "emission reduction policy",
    "emission reduction target policy",
    "emission regulation",
    "emission tax",
    "emission tax coordination",
    "emissions allowances",
    "emissions compliance market",
    "emissions leakage",
    "emissions permits",
    "emissions trading schemes",
    "empirical-research",
    "empirical approach",
    "empirical mode decomposition",
    "empirical orthogonal function (eof)",
    "employee turnover",
    "employment implications",
    "empowerment",
    "enabling conditions",
    "end of pipe intervention", 
        "yield", "young-people", "youth participation", "'hot' law",
    "-mexico border", "-mexico border region", "(eafm)", "(sic)(sic)", "??", "????", "?????",
    "1) model", "10 oecd countries", "11th five-year plan", "1972 unche",
    "1st amendment", "1st nations", "2 °c target", "2015", "2022 stockholm+50",
    "2030 agenda for sustainable development", "2100", "2sls", "3 decades", "5-year plan",
    "5 exposure", "a community of shared future for humanity", "abandonment",
    "abate carbon emissions", "abatement", "abnormal returns", "abnormal temperature",
    "above-ground carbon stocks", "absorptive capacity", "abstraction licensing",
    "acceptability", "acceptance", "access to information", "accession", "accidents",
    "accounting", "accounting information quality", "accumulations", "accuracy",
    "acetylene-reduction", "acid-batteries", "act", "actiniaria", "action", "action plans",
    "action research", "action situations", "active community", "activities in the area",
    "actor-network theory", "actor identification", "actor diversity", "actorness",
    "adaptive cycle", "addis ababa", "additives", "adenike akinsemolu", "adjudication",
    "administration", "administrative procedures", "advanced panel",
    "advanced panel data estimator", "advocacy", "advocacy coalitions",
    "aerosol", "afforestation", "african countries", "age", "age structural transition",
    "agency costs", "agenda for practice", "agenda setting", "agent-based model",
    "agglomeration", "agglomeration externalities", "agrarian and food justice",
    "agreement process", "agri-environmental measures", "agri-environmental policies",
    "agri-environmental schemes", "agri-food tech", "agricultural carbon emission",
    "agricultural carbon intensity", "agricultural commercialization",
    "agricultural development", "agricultural extension",
    "agricultural green total factor productivity", "agricultural intensification",
    "agricultural land carbon emissions", "agricultural mechanization",
    "agricultural modernization", "agricultural production", "agricultural waste",
    "agrofuel", "aid", "aiptasia-pallida", "air-quality regulations",
    "air pollutant control", "air pollution control",
    "air pollution law and policy", "air pollution management",
    "air pollution prevention and control action plan", "air protection",
    "air quality index", "air voids", "airport", "alaska", "algae", "algorithm",
    "algorithms", "alignments", "alleviation", "alliances", "allowances price",
    "alpine grassland", "alpine grasslands", "alpine vegetation phenology",
    "alternative framework", "alternative protein", "altitude differentiation",
    "altitudinal planning", "alumina refinery", "ambiguity", "american",
    "american convention on human rights", "american west", "amsterdam",
    "anaerobic oxidation", "analysis", "analyst forecast", "analytic deliberation",
    "analytic hierarchy process", "analytical framework",
    "analytical hierarchy process", "ancillary benefits", "and africa",
    "and competences", "and local politics", "and mayors", "and n-11 economies",
    "androgens", "annual cycles", "annual phenological cycle",
    "antarctica", "anthropogenic source", "anti-consumption", "anti-corruption",
    "anti-reflexivity", "antibiotic-resistance", "antimicrobial resistance",
    "apec countries", "appliances", "appointed directors", "aqi", "aquacrop model",
    "aquaculture", "aquatic ecology", "aquifer storage", "arabian gulf",
    "arbitrating", "arbitration clause", "archaeology", "architecture",
    "arctic mining", "arctic ocean oscillation", "arctic petroleum production",
    "arctic region", "arctic research station", "arctic sea ice",
    "arctic shipping", "arctic sovereignty", "arctica-islandica",
    "ardl", "areas beyond national jurisdiction (abnj)", "arms-length",
    "arsenic regulation", "art", "arthropoda", "articulation", "artifacts",
    "artisanal mining", "asean economies", "asexual reproduction",
    "asia developing countries", "asia pacific environment", "asian capitalism",
    "asian countries interaction effect model", "assessment framework",
    "assessment lca", "assessment system", "assessments", "asset management",
    "assumptions", "astronomy", "asymmetric governance systems",
    "asymmetric warming", "atlantic forest", "atlantic multidecadal oscillation",
    "atmospheres", "atmospheric movements", "atmospheric particles",
    "atmospheric plume", "atolls", "attachment", "attenuation", "auctions",
    "audience", "audit fees", "augmented difference in differences",
    "australia's forests", "australian scholarship", "austria",
    "authoritarian regime", "autocorrelation", "autocracy", "autocratic regimes",
    "automation", "autonomy", "avian predator", "aviation", "awards", "backyard",
    "bahia blanca", "balance", "ballast water management",
    "baltic sea time machine", "bank", "bank loans", "banking sector",
    "barcelona", "barents-sea", "bari doab", "barriers and strategies",
    "base-line characterization", "base-lines", "basin perspectives", "basins",
    "bass", "bayesian estimation", "bayesian modeling", "bayesian network",
    "bayesian network model", "bayesian shrinkage estimator", "bbnj instrument",
    "beaufort sea", "beekeepers", "behavior change", "behavioral intentions",
    "behavioral research", "behavioral strategies of stakeholders",
    "behaviorism", "behaviors", "beijing", "beijing [china]", "belt",
    "belt and road initiative", "benefit", "benthic fisheries", "berlin",
    "best-worst scaling", "best practices", "beta", "betula-pendula",
    "bhutan", "bi-level modeling", "bibliometric methods",
    "bibliometric network analysis", "bibliometrics", "biblioshiny", "big",
    "bilateral agreement", "bilateral cooperation", "biodegradation",
    "biodiversity policy", "biodiversity preservation",
    "bioeconomy", "bioethics", "biofuel policy", "biofuels policy",
    "biofuels process synthesis", "biogas", "biological integrity",
    "biological soil crusts", "biomass allocation", "biopolitics",
    "biopower", "biorefinery", "biosecurity", "biotechnology",
    "bird reproduction", "bitcoin", "bivalve growth", "bivariate spatial autocorrelation",
    "blackcurrant", "blame", "blast-furnace slag", "bleaching technologies",
    "blockchain technology", "blue-green infrastructure", 
    "blue and green spaces", "blue carbon", "blue space", "blue spaces",
    "board", "board capital", "board gender", "board gender diversity",
    "board independence", "board specialty", "boards", "body condition",
    "bogong high-plains", "bohai sea", "bolivia", "bond", "border adjustment",
    "borders", "boreal ecosystem", "boreal ecosystem productivity simulator",
    "boreal forest", "boreal trees", "bottom-up approach", "boundary",
    "boundary-work", "boundary arrangements", "boundary effect",
    "boundary organisations", "boundary organization", "bourdieu",
    "bp neural-network", "bp neural network model", "br-163", "brandenburg",
    "brasil", "brazilian amazon", "brazilian companies", "brazilian foreign policy",
    "brazilian soya", "breakpoint unit root tests", "breath",
    "bridge organization", "bridges", "bridging knowledge systems",
    "brief conceptual tutorial", "britain", "brokerage", "brood patch",
    "bth", "budget", "budget or time", "buds", "building",
    "building adaptive capacity", "building energy efficiency",
    "building institutional capacity", "bushfire", "bushfire fatalities",
    "bushfires", "business-cycle", "business-government relations",
    "business and human rights", "business and the environment",
    "business decarbonization", "business environment", "business environmental strategies",
    "business performance",
        "futures", "game", "genders", "happiness", "hard", "hazards",
    "heterogeneity", "heterogeneity analysis", "heterogeneous panels",
    "high-quality development", "households", "humans", "hydrological processes",
    "ideas", "identification", "imaginaries", "immune-system", "innovation evidence",
    "intention", "interests", "investor-state dispute settlement", "islands",
    "issue-attention cycle", "kernel density estimation", "lakes", "life",
    "liminality", "maize", "matter", "mechanism", "mediating role", "mediation",
    "metrics", "metropolitan", "middle-east", "moderating effect", "moderating role",
    "motivation", "nardl", "native vegetation", "natural environment", "nature",
    "ndvi", "need", "norms", "north", "oecd", "organic-carbon", "paradigm",
    "paradigm shift", "path", "penalty", "pipeline", "plants", "plateau",
    "pm2 5", "practice", "prevention", "price", "primary productivity", "private",
    "program", "programs", "propensity score", "protest", "protocol",
    "psychological distance", "q54", "quantitative methods", "recovery",
    "relationships", "reproduction", "research agenda", "responsibilities",
    "risk reduction", "roles", "rule", "s", "scalar politics", "scarcity",
    "scenario analysis", "scheme", "seasonal variation", "selection",
    "self-organization", "sense", "sensemaking", "sensitivity", "sequestration",
    "skills", "slow", "storage", "sts", "super-sbm", "system dynamics",
    "targets", "temporal dynamics", "temporality", "terrestrial", "testosterone",
    "thinking", "treadmill", "turnover", "twenty first century", "u",
    "war", "welfare", "women",
        "ice", "ict", "inclusion", "income", "index", "industrialization",
    "interannual variability", "interdisciplinary", "intermediary effect",
    "internet", "investments", "knowledge exchange", "knowledge politics",
    "land management", "livestock", "lobbying", "logistics", "machine learning",
    "materiality", "mechanism analysis", "mediating effect", "mmqr", "monitoring",
    "mortality", "movement", "movements", "natural resource", "natural resource management",
    "ontology", "patent", "pathways", "permits", "planning", "plans", "plus",
    "practice", "precipitation", "products", "project", "projects", "proximity",
    "quantities", "recognition", "reparations", "returns", "safeguards",
    "satisfaction", "schemes", "scientific advice", "sea", "simulation",
    "society", "statistical analysis", "stock", "stock-market", "stocks",
    "struggles", "subsidy", "supply chain", "sweden", "technology adoption",
    "text", "threshold effect", "time", "tool", "tourism", "transparency",
    "unit-root", "work", "youth", "abundance", "action plan", "adaptability",
    "adaptive behavior", "adaptive system", "adjacent action situations",
    "adult", "age structure", "agreement", "air", "assessment", "atmosphere",
    "austerity", "available techniques", "awareness", "belief systems",
    "beliefs", "belonging", "benchmarking", "bioenergy", "biofuel",
    "biological diversity", "boundaries", "boundary work", "buildings",
    "businesses", "chains", "challenge", "circulation", "citizenship",
    "cognition", "comparative study", "constructions", "consultation",
    "consumerism", "consumers", "content analysis", "contiguity", "convergence",
    "country", "cycle", "data management", "decisions", "defense", "demand",
    "dilemmas", "distance", "earnings", "economic aspect", "economic efficiency",
    "economic impact", "ecosystem management", "ecosystem service",
    "education", "efficiency improvement", "electricity", "elite capture",
    "end", "energy structure", "energy transitions", "energy use", "energy utilization",
    "entrepreneurship", "environment regulation", "environmental-change",
    "environmental-protection", "environmental agreements",
    "environmental attitudes", "environmental history", "environmental impacts",
    "environmental knowledge", "environmental operations",
    "environmental principles", "environmental services", "environmental state",
    "environmental trade-offs", "environmental transitions", "environmentalism",
    "event", "experience", "failure", "feedback", "financial stability", "fire",
    "fish", "fit", "footprint", "footprints", "freshwater", "frontiers",
        # muy genéricas / poco informativas de este bloque
    "prices",
    "space",
    "standards",
    "tests",
    "time-series",
    "world",
    "access",
    "actors",
    "companies",
    "firm",
    "firm performance",
    "generation",
    "identity",
    "inequality",
    "landscape",
    "media coverage",
    "methodology",
    "natural resources",
    "negotiations",
    "network analysis",
    "optimization",
    "patterns",
    "region",
    "regions",
    "services",
    "support",
    "tax",
    "taxes",
    "territory",
    "vegetation",
    "views",
    "allocation",
    "choice",
    "classification",
    "commitment",
    "conflicts",
    "coordination",
    "crisis",
    "culture",
    "development",
    "difference",
    "disaster",
    "drought",
    "ecosystems",
    "emerging economies",
    "emission",
    "employment",
    "enterprises",
    "environmental issue",
    "environmental impact",
    "environmental monitoring",
    "environmental outcomes",
    "environmental performance",
    "environmental research",
    "environmental strategy",
    "experiences",
    "exploitation",
    "export",
    "exports evidence",
    "exposure",
    "gains",
    "growth evidence",
    "history",
    "issues",
    "instruments",
    "ownership",
    "peoples",
    "prediction",
    "prospects",
    "property",
    "property-rights",
    "reflections",
    "rise",
    "risks",
    "scales",
    "soil",
    "stormwater",
    "support",
    "translation",
    "transportation",
    "typology",
    "views",
    "weather",
    "food",
        "impact", "impacts", "future", "growth", "knowledge", "performance",
    "participation", "conservation", "science", "framework", "environment",
    "environmental sustainability", "state", "power", "countries", "economy",
    "industry", "information", "justice", "decision making", "decision-making",
    "system", "systems", "article", "benefits", "evolution", "globalization",
    "human", "level", "organization", "organizations", "agency", "agenda",
    "areas", "cost", "costs", "context", "place", "perspective", "perspectives",
    "models", "network", "panel", "values", "scenarios", "sector",
    "technologies", "trends", "waste", "outcomes", "drivers",
    "driving factors", "responses", "opportunities", "insights",
    "lessons", "reduction", "protection", "implementation", "determinants",
    "quality", "research", "development", "market", "markets",
    "city", "cities", "business", "government", "governance approach", 



]

# Función para eliminar palabras clave específicas y retornar una cadena
def eliminar_palabras_clave(column):
    # Convertir la lista de palabras clave a eliminar a minúsculas
    palabras_clave_a_eliminar_lower = [palabra.lower() for palabra in palabras_clave_a_eliminar]
    
    def process_cell(cell):
        # Si la celda es una cadena, la dividimos en una lista usando el separador ';'
        if isinstance(cell, str):
            terminos = [termino.strip() for termino in cell.split(';') if termino.strip()]
        # Si ya es una lista, la usamos directamente
        elif isinstance(cell, list):
            terminos = [str(termino).strip() for termino in cell if str(termino).strip()]
        else:
            terminos = []
        # Filtrar los términos que, al pasar a minúsculas, estén en la lista a eliminar
        terminos_filtrados = [termino for termino in terminos if termino.lower() not in palabras_clave_a_eliminar_lower]
        # Unir la lista filtrada en una cadena usando '; ' como separador
        return '; '.join(terminos_filtrados)

    return column.apply(process_cell)
print("Antes (recuento únicos):")
for c in KW_COLS:
    if c in df.columns:
        nuniq = df[c].dropna().str.split(';').explode().str.strip().replace("", pd.NA).dropna().nunique()
        print(f"  {c}: {nuniq}")
# Aplicar la función a las columnas "Index Keywords" y "Author Keywords"
df['Index Keywords'] = eliminar_palabras_clave(df['Index Keywords'])
#df['bothKeywords'] =  eliminar_palabras_clave(df['bothKeywords'])
df['Author Keywords'] = eliminar_palabras_clave(df['Author Keywords'])
# Guardar el DataFrame filtrado en un nuevo archivo CSV
print("\nDespués (recuento únicos):")
for c in KW_COLS:
    if c in df.columns:
        nuniq = df[c].dropna().str.split(';').explode().str.strip().replace("", pd.NA).dropna().nunique()
        print(f"  {c}: {nuniq}")
# Construir listado global normalizado
all_terms = pd.concat([
    df['Index Keywords'].dropna(),
    df['Author Keywords'].dropna()
]).str.split(';').explode().str.strip()

# Frecuencia sobre versión normalizada
freq = all_terms.str.lower().value_counts()
keep_norm = set(freq[freq > 1].index)

def filter_unique(cell):
    if not isinstance(cell, str):
        return ""
    terms = [t.strip() for t in cell.split(';') if t.strip()]
    filtered = [t for t in terms if t.lower() in keep_norm]
    return '; '.join(filtered)
#df['Index Keywords'] = df['Index Keywords'].apply(filter_unique)
#df['Author Keywords'] = df['Author Keywords'].apply(filter_unique)
# Guardar el DataFrame filtrado en un nuevo archivo CSV
#df.to_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv", index=False)

df.to_csv(r"G:\Mi unidad\2025\Master  FRANCISCO MARCELO ALVARADO PORRAS\data\datawos_scopuseliminar2.csv", index=False)
print("Palabras clave específicas eliminadas y nuevo archivo guardado.")
