import pandas as pd

# Cargar el archivo CSV
#df = pd.read_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv")

df = pd.read_csv(r"G:\Mi unidad\2025\master karla mora\new article scopus\data\datawos_scopusnormalizar.csv")
   # Lista de palabras clave a eliminar (en minúsculas)
palabras_clave_a_eliminar = [

   "cross cultural comparison",
    "cultural anthropology",
    "depth perception",
    "digital medium",
    "drawing",
    "eating",
    "efficacy",
    "exercise",
    "externalizing disorder",
    "eye movement",
    "family history",
    "fetal alcohol spectrum disorder",
    "food insecurity",
    "fragile syndrome",
    "germany",
    "government",
    "growth curve",
    "health care access",
    "health care planning",
    "health care quality",
    "impairment",
    "infant nutritional physiological phenomenon",
    "input",
    "intention to treat analysis",
    "investment",
    "linear model",
    "malawi",
    "mediation",
    "mental performance",
    "mortality",
    "motor coordination",
    "movement assessment battery for child",
    "multivariate analysis",
    "norway",
    "nutritional assessment",
    "occupational therapy",
    "paediatric patient",
    "partner violence",
    "patient referral",
    "predictive validity",
    "preterm birth",
    "prognosis",
    "protective factor",
    "psycho education",
    "psychological well being",
    "psychomotor development",
    "psychopathology",
    "punishment",
    "quasi experimental study",
    "recognition",
    "responsibility",
    "school age child",
    "sensitivity and specificity",
    "sleep disorder breathing",
    "social determinant of health",
    "stereotypy",
    "substance use",
    "tel medicine",
    "thematic analysis",
    "turkey bird",
    "videoconferencing",
    "visual perception",
    "academic performance",
    "accuracy",
    "adaptation",
    "adverse event",
    "aging",
    "anti convulsive agent",
    "artificial ventilation",
    "asthma",
    "attention deficit and disruptive behavior disorder",
    "attention disturbance",
    "black person",
    "childhood autism rating scale",
    "classroom",
    "cleft lip",
    "communication aid",
    "community health worker",
    "conduct disorder",
    "confidence interval",
    "convergent validity",
    "cortisol",
    "cost effectiveness analysis",
    "cranach alpha coefficient",
    "datum extraction",
    "deprivation",
    "diarrhoea",
    "diet supplementation",
    "differential susceptibility",
    "discipline",
    "double blind procedure",
    "early",
    "electronic book",
    "elementary school",
    "emotional abuse",
    "empowerment",
    "ethnic group",
    "evaluation study",
    "experimental study",
    "family conflict",
    "family life",
    "family stress",
    "family therapy",
    "ghana",
    "head",
    "health care utilization",
    "health literacy",
    "high risk population",
    "hong kong",
    "household chaos",
    "individual",
    "interaction",
    "internalizing disorder",
    "latent class analysis",
    "low income family",
    "marriage",
    "medical education",
    "mental health service",
    "mexico",
    "middle income group",
    "mobile application",
    "motor",
    "netherland",
    "night sleep",
    "nutrition education",
    "otitis medium",
    "paediatric quality of life inventory",
    "pandemics",
    "patient education",
    "patient report outcome",
    "perception deafness",
    "physician",
    "physiological stress",
    "post how analysis",
    "pregnancy outcome",
    "premature labour",
    "pro social behavior",
    "psychiatric status rating scale",
    "psycho logic test",
    "psychological test",
    "puerperium",
    "sickle cell anaemia",
    "social network",
    "spas version",
    "speak language",
    "spring",
    "stuttering",
    "symptomatology",
    "taiwan",
    "technology",
    "television viewing",
    "trace element",
    "unclassified drug",
    "united kingdom",
    "university",
    "urban area",
    "adulthood",
    "affect",
    "age and stage questionnaire",
    "alcohol",
    "alcohol consumption",
    "anaemia",
    "app",
    "arithmetic",
    "asian",
    "augmentative and alternative communication",
    "autism assessment",
    "autism diagnostic interview revise",
    "blood",
    "brain mapping",
    "caregiver burden",
    "caregiving",
    "case study",
    "child foster",
    "child maltreatment",
    "child psychiatry",
    "chile",
    "chromosome",
    "chronic disease",
    "classroom quality",
    "colombia",
    "community",
    "community child health",
    "community sample",
    "complementary feeding",
    "computer simulation",
    "conceptual framework",
    "conduct problem",
    "confirmatory factor analysis",
    "conflict",
    "consultation",
    "content validity",
    "cultural characteristic",
    "denmark",
    "depression postpartum",
    "developmental neurology near disability",
    "developmental stage",
    "diagnostic accuracy",
    "diffusion tensor imaging",
    "early head start",
    "early identification",
    "early year",
    "education and care",
    "emotional intelligence",
    "england",
    "episodic memory",
    "event relate potential",
    "externalizing behavior problem",
    "faculty",
    "family structure",
    "family study",
    "food",
    "fractional anisotropy",
    "gene",
    "gene deletion",
    "genetic transcription",
    "genotype",
    "genotype environment interaction",
    "health care cost",
    "health care policy",
    "health disparity",
    "hearing disorder",
    "hospital",
    "housing",
    "human immunodeficiency virus",
    "hydrocortisone",
    "individuality",
    "infant direct speech",
    "infant sibling",
    "intervention strategy",
    "interview as topic",
    "intrauterine growth retardation",
    "juvenile",
    "learning activity",
    "logistic model",
    "mathematical concept",
    "mathematical phenomena",
    "memory disorder",
    "mental disease assessment",
    "middle childhood",
    "mindfulness",
    "mobile app",
    "model statistical",
    "mood",
    "mother infant",
    "music",
    "near developmental outcome",
    "neglect",
    "nerve cell plasticity",
    "neurologic examination",
    "new zealand",
    "number",
    "onset age",
    "opiate",
    "oppositional defiant disorder",
    "parent implement intervention",
    "parent input",
    "parenting practice",
    "parenting stress index",
    "perinatal period",
    "philippine",
    "policy",
    "polygon biography",
    "premature birth",
    "premature infant",
    "preschool education",
    "prevention and control",
    "psycho logic assessment",
    "psychological aspect",
    "psychosocial disorder",
    "race difference",
    "randomization",
    "receptive vocabulary",
    "resilience",
    "respiratory sinus arrhythmia",
    "risk reduction",
    "sanitation",
    "scale",
    "screen medium",
    "security",
    "self care",
    "sensory dysfunction",
    "singapore",
    "sleep apnoea obstructive",
    "smartphone",
    "spanish",
    "spatial skill",
    "special situation for pharmacy vigilance",
    "speech and language assessment",
    "speech and language rehabilitation",
    "statistical analysis",
    "statistical significance",
    "structure questionnaire",
    "study design",
    "survey",
    "survivor",
    "teacher child interaction",
    "teacher training",
    "telephone interview",
    "thailand",
    "tonsillectomy",
    "total quality management",
    "touch",
    "touch screen tablet",
    "treatment response",
    "twin",
    "up genetic",
    "vaccination",
    "verbal memory",
    "very low birth weight",
    "violence",
    "walking",
    "activity of daily living",
    "adenoidectomy",
    "adolescent behavior",
    "adolescent mother",
    "adopt child",
    "adoption",
    "alertness",
    "altimetry",
    "anaemia sickle cell",
    "and middle income country",
    "anger",
    "antecedent",
    "anti convulsant",
    "anti retrovirus agent",
    "arcuate fasciculus",
    "attachment security",
    "auditory rehabilitation",
    "autonomy support",
    "bayes theorem",
    "behavioural observation",
    "behavioural problem",
    "behavioural regulation",
    "blood sampling",
    "body composition",
    "breastfeeding",
    "caloric intake",
    "cannabis",
    "caregiver training",
    "chromosome deletion",
    "clinical assessment tool",
    "communication and language",
    "congenital heart disease",
    "control group",
    "counting",
    "cross cultural",
    "dam in",
    "deficit",
    "delivery of health care integrate",
    "depressive symptom",
    "diagnostic and statistical manual of mental disorder",
    "difficulty questionnaire",
    "disease",
    "disease course",
    "disease predisposition",
    "disorder of high cerebral function",
    "drug safety",
    "early learning",
    "east asian",
    "east asian people",
    "eating behavior",
    "emotion socialization",
    "emotional adjustment",
    "empathy",
    "european american",
    "expressive vocabulary",
    "externalizing problem",
    "extra textual talk",
    "eye fixation",
    "facial recognition",
    "familial risk",
    "family engagement",
    "family environment",
    "fatigue",
    "feasibility",
    "feeding",
    "fixation ocular",
    "food preference",
    "foster",
    "fri",
    "frustration",
    "functional assessment",
    "functional near imaging",
    "functional near infrared spectroscopy",
    "games",
    "gene mutation",
    "genetic screening",
    "genetic variability",
    "glasgow coma scale",
    "group therapy",
    "growth disorder",
    "habit",
    "haemoglobin",
    "health practitioner",
    "health relate quality of life",
    "health service accessibility",
    "high risk",
    "high school",
    "hispanic or latino",
    "home mathematics environment",
    "hospital discharge",
    "human immunodeficiency virus infect patient",
    "imitative behavior",
    "immigrant",
    "implementation",
    "impulsivity",
    "indigenous people",
    "infant very low birth weight",
    "infection",
    "insomnia",
    "institutional care",
    "instructional strategy",
    "internalization behavior",
    "intervention psychosocial behavioural",
    "intimate partner violence",
    "length of stay",
    "literacy practice",
    "locomotion",
    "long term care",
    "low and middle income country",
    "match skill",
    "maternal care",
    "maternal exposure",
    "maternal mental health",
    "maternal responsively",
    "mathematical competency",
    "mental task",
    "methadone",
    "methylene date",
    "micronutrient",
    "migration",
    "minimally verbal",
    "motor control",
    "multiple linear regression analysis",
    "nepal",
    "nerve cell network",
    "numeracy environment",
    "nursing",
    "orphanage",
    "overweight",
    "parent education",
    "parent perception",
    "parent report",
    "participatory research",
    "path analysis",
    "patient attitude",
    "patient compliance",
    "patient education as topic",
    "patient health questionnaire",
    "personality",
    "physiotherapy",
    "pivotal response treatment",
    "population",
    "postnatal care",
    "predictive value of test",
    "prenatal alcohol exposure",
    "prenatal drug exposure",
    "primary care",
    "progeny",
    "program effectiveness",
    "protection",
    "psycholinguistic",
    "psychomotor disorder",
    "psychosocial care",
    "psychosocial intervention",
    "quality of life assessment",
    "quantity",
    "question",
    "randomise control trial",
    "reading skill",
    "redline",
    "regression model",
    "resilience psychological",
    "response time",
    "role playing",
    "science",
    "scientist",
    "screening tool",
    "self esteem",
    "social isolation",
    "social learning",
    "social problem",
    "social validity",
    "software",
    "special education",
    "speech articulation",
    "stage sleep",
    "standardization",
    "substance abuse",
    "supplementation",
    "surgery",
    "symptom assessment",
    "toddler hood",
    "trend",
    "turn taking",
    "val proc acid",
    "validation",
    "validation process",
    "vertical transmission",
    "victoria",
    "vocabulary intervention",
    "voice",
    "wakefulness",
    "word gap",
    "write language",
    "zimbabwe",
    "acute lymphoblast leukaemia",
    "adaptive functioning",
    "aden tonsillectomy",
    "agar score",
    "anthropometric parameter",
    "anti retro viral agent",
    "antibiotic agent",
    "antidepressant agent",
    "antisocial behavior",
    "aphasia",
    "apnoea hypo new index",
    "asia",
    "attention network test",
    "auditory discrimination",
    "auditory screening",
    "augmentative and alternative communication mac",
    "bear",
    "behavior control",
    "bilingual child",
    "biological marker",
    "brain region",
    "bruin ink sere sky test of motor proficiency",
    "calculation",
    "cancer survivor",
    "caregiver input",
    "caregiver perception",
    "caregiver responsiveness",
    "caregiver training program",
    "cerebellum",
    "child communication checklist",
    "child institutionalize",
    "child nutrition disorder",
    "child safety",
    "childbirth",
    "childhood cancer",
    "childhood development",
    "clinical decision making",
    "clinical trial protocol",
    "clinician",
    "community health service",
    "complex communication need",
    "concurrent validity",
    "congenital heart malformation",
    "content analysis",
    "continuous performance test",
    "cooperative behavior",
    "coordination",
    "creativity",
    "cultural diversity",
    "datum base",
    "de contextualized language",
    "deficit hyperactivity disorder",
    "delivery of health care",
    "denver developmental screening test",
    "depressive disorder major",
    "develop country",
    "developmental screening",
    "diagnostic test accuracy study",
    "diet healthy",
    "disability population",
    "disease exacerbation",
    "disease severity assessment",
    "diversity",
    "docosahexaenoic acid",
    "doctor patient relation",
    "drug dependence",
    "duration",
    "early adversity",
    "early childhood",
    "early development",
    "early life stress",
    "early numeracy skill",
    "electrophysiology",
    "emergence",
    "emotional regulation",
    "emotional stability",
    "emotional stress",
    "emotional support",
    "english language learner",
    "ethnic difference",
    "europe",
    "evoke potential",
    "evoke response",
    "exceptional tie",
    "executive control",
    "extension",
    "externalization behavior",
    "family health",
    "family literacy practice",
    "fear",
    "first trimester pregnancy",
    "fitness",
    "food security",
    "forecasting",
    "functional status",
    "game",
    "gender difference",
    "gene environment interaction",
    "genetic analysis",
    "genetic disorder",
    "genetic predisposition",
    "geometry",
    "gross motor function classification system",
    "group dynamic",
    "growth and development",
    "happiness",
    "health care",
    "health care need",
    "health care organization",
    "health insurance",
    "health personnel",
    "health personnel attitude",
    "hearing loss bilateral",
    "hearing loss sensor neural",
    "hearing test",
    "heart defect congenital",
    "heart rate",
    "heart rate variability",
    "high risk infant",
    "high risk patient",
    "home stimulation",
    "home visiting intervention",
    "homelessness",
    "hospital admission",
    "hygiene",
    "hype scanning",
    "immunization",
    "implementation science",
    "impulsive behavior",
    "indian",
    "indigenous",
    "infectious disease transmission vertical",
    "inform consent",
    "informal learning",
    "intellectual assessment",
    "interaction therapy",
    "interest",
    "intrusiveness",
    "irritability",
    "kaufman assessment battery for child",
    "kindergartener",
    "language and literacy",
    "language environment",
    "language environment analysis",
    "language learning",
    "language network",
    "language skill",
    "latin family",
    "latino",
    "lead",
    "leadership",
    "lena",
    "level raceway",
    "life event",
    "lifespan",
    "lifestyle",
    "link",
    "literacy promotion",
    "live birth",
    "long term outcome",
    "low risk population",
    "lung dysplasia",
    "machine learning",
    "major depression",
    "malaria",
    "mass screening",
        "human",
    "female",
    "male",
    "article",
    "infant",
    "control study",
    "major clinical study",
    "adult",
    "human experiment",
    "physiology",
    "questionnaire",
    "priority journal",
    "autism",
    "adolescent",
    "clinical article",
    "follow up",
    "procedure",
    "autism spectrum disorder",
    "outcome assessment",
    "newborn",
    "cohort analysis",
    "age",
    "risk factor",
    "path physiology",
    "mental health",
    "prospective study",
    "cross sectional study",
    "pregnancy",
    "survey and questionnaire",
    "young adult",
    "socioeconomic status",
    "social status",
    "review",
    "poverty",
    "complication",
    "socioeconomic",
    "clinical trial",
    "child health",
    "comparative study",
    "educational status",
    "systematic review",
    "autistic disorder",
    "video recording",
    "bailey scale of infant development",
    "multi enter study",
    "quality of life",
    "hearing impairment",
    "united states",
    "depression",
    "developmental delay",
    "near psychological test",
    "infancy",
    "randomize control trial topic",
    "outcome",
    "association",
    "treatment outcome",
    "prevalence",
    "age factor",
    "developmental disorder",
    "follow up study",
    "prematurity",
    "socioeconomic factor",
    "adaptive behavior",
    "brain",
    "down syndrome",
    "mental disease",
    "developmental disability",
    "interview",
    "paediatric",
    "cognitive defect",
    "cohort study",
    "human tissue",
    "sleep",
    "disease severity",
    "meta analysis",
    "pilot study",
    "scoring system",
    "sex difference",
    "household",
    "clinical assessment",
    "human relation",
    "language disability",
    "low income group",
    "anxiety",
    "china",
    "risk assessment",
    "environment",
    "health",
    "observational study",
    "psychometry",
    "rural population",
    "screen time",
    "speech therapy",
    "demography",
    "epidemiology",
    "gender",
    "hearing loss",
    "low income",
    "prenatal exposure",
    "speech disorder",
    "nutrition",
    "predictor",
    "time factor",
    "behavior assessment",
    "case control study",
    "language therapy",
    "south africa",
    "case report",
    "child abuse",
    "disease association",
    "head start",
    "cochlear implant",
    "nuclear magnetic resonance imaging",
    "physical activity",
    "prediction",
    "randomize control trial as topic",
    "therapy",
    "with hyperactivity",
    "birth weight",
    "child nutrition",
    "clinical outcome",
    "feasibility study",
    "gestational age",
    "hispanic",
    "intellectual disability",
    "quality",
    "reliability",
    "genetic",
    "longitudinal",
    "nutritional status",
    "social class",
    "speech language pathologist",
    "australia",
    "autism diagnostic observation schedule",
    "deafness",
    "normal human",
    "health program",
    "human immunodeficiency virus infection",
    "mental stress",
    "pilot project",
    "regression analysis",
    "speech analysis",
    "child health care",
    "coping behavior",
    "ethnicity",
    "income",
    "middle income country",
    "public health",
    "statistical model",
    "structural equation modelling",
    "add",
    "aggression",
    "behavior therapy",
    "diagnosis",
    "model",
    "near imaging",
    "phenotype",
    "self report",
    "stress",
    "stress psychological",
    "aged",
    "attitude to health",
    "auto regulation",
    "child behavior disorder",
    "eye tracking",
    "health promotion",
    "involvement",
    "near psychological assessment",
    "near psychology",
    "recreation",
    "sibling",
    "social evolution",
    "statistic and numerical datum",
    "accelerating language development",
    "adaptation psychological",
    "african american",
    "assessment",
    "cerebral palsy",
    "chinese",
    "demographic",
    "education nonprofessional",
    "electroencephalography",
    "infant premature",
    "inter rater reliability",
    "intervention study",
    "methodology",
    "nonhuman",
    "obesity",
    "performance",
    "program",
    "reproducibility",
    "reproducibility of result",
    "rural area",
    "anthropometry",
    "brain function",
    "clinical effectiveness",
    "cluster analysis",
    "control clinical trial",
    "cultural factor",
    "developing country",
    "environmental factor",
    "his infection",
    "prenatal exposure delay effect",
    "seizure",
    "well being",
    "behavior change",
    "breast feeding",
    "child rearing",
    "cochlear implantation",
    "experience",
    "feeding behavior",
    "growth",
    "instruction",
    "maternal depression",
    "meet cognition",
    "postnatal depression",
    "speech delay",
    "vineland adaptive behavior scale",
    "adolescence",
    "child growth",
    "cochlea prosthesis",
    "communication disorder",
    "day care",
    "electroencephalogram",
    "engagement",
    "family size",
    "hyperactivity",
    "impact",
    "maternal age",
    "mullen scale of early learning",
    "near development",
    "pregnant woman",
    "primary medical care",
    "print",
    "rating scale",
    "research design",
    "semi structured interview",
    "sex factor",
    "single blind procedure",
    "spectrum disorder",
    "speech language pathology",
    "stimulation",
    "body weight",
    "family income",
    "foster care",
    "health survey",
    "india",
    "match",
    "organization and management",
    "personal experience",
    "predictive value",
    "prenatal care",
    "program evaluation",
    "psychometric",
    "sleep disorder",
    "student",
    "talk",
    "traumatic brain injury",
    "validity",
    "assessment of human",
    "care behavior",
    "caregiver support",
    "checklist",
    "daily life activity",
    "decision making",
    "evidence base practice",
    "gaze",
    "he",
    "health care delivery",
    "health education",
    "health status",
    "household income",
    "internal consistency",
    "magnetic resonance imaging",
    "outcome assessment health care",
    "primary health care",
    "primary school",
    "quantitative analysis",
    "responsiveness",
    "sample size",
    "self concept",
    "sleep time",
    "social psychology",
    "storytelling",
    "and",
    "bangladesh",
    "body mass",
    "brazil",
    "caregiver child interaction",
    "corona virus disease",
    "growth development and aging",
    "health care personnel",
    "low birth weight",
    "paediatrician",
    "practice guideline",
    "semantic",
    "sensitivity",
    "social aspect",
    "strategy",
    "treatment duration",
    "vision",
    "age distribution",
    "care",
    "child welfare",
    "delay",
    "descriptive research",
    "drug effect",
    "exposure",
    "health service",
    "hearing aid",
    "hearing impair person",
    "intelligence test",
    "language disorder",
    "learning disorder",
    "maternal welfare",
    "nurse",
    "pathology",
    "peabody picture vocabulary test",
    "prevention",
    "professional development",
    "retrospective study",
    "rural china",
    "self efficacy",
    "sensitivity analysis",
    "standard",
    "strength and difficulty questionnaire",
    "support",
    "trajectory",
    "urban population",
    "we chol intelligence scale for child",
    "we chol preschool and primary scale of intelligence",
    "birth cohort",
    "brain injury",
    "child neglect",
    "childhood disease",
    "cognitive behavioural therapy",
    "comparative effectiveness",
    "culture",
    "curriculum",
    "datum analysis",
    "diet",
    "domestic violence",
    "environmental exposure",
    "ethnology",
    "exploratory research",
    "functional magnetic resonance imaging",
    "girl",
    "health auxiliary",
    "health behavior",
    "health knowledge attitude practice",
    "inhibition psychological",
    "internet",
    "language impairment",
    "liker scale",
    "nerve cell differentiation",
    "person with hearing impairment",
    "pret post test design",
    "psychomotor performance",
    "qualitative analysis",
    "speech intelligibility",
    "tanzania",
    "television",
    "test retest reliability",
    "uganda",
    "anxiety disorder",
    "attitude",
    "audio recording",
    "belief",
    "bilingualism",
    "book reading",
    "child psychology",
    "childhood obesity",
    "clinical evaluation",
    "clinical feature",
    "clinical protocol",
    "cognitive control",
    "cognitive function test",
    "competence",
    "deaf",
    "device",
    "disabled child",
    "distress syndrome",
    "dyslexia",
    "early medical intervention",
    "expressive language",
    "facial expression",
    "handicapped child",
    "imitation",
    "infant behavior",
    "latent profile analysis",
    "linear regression analysis",
    "maternal sensitivity",
    "mental disorder",
    "near developmental disorder",
    "peer group",
    "physical development",
    "pretend play",
    "psychology child",
    "screening",
    "service",
    "stunting",
    "test",
    "therapy effect",
    "visual attention",
    "vocabulary acquisition",
    "ability",
    "adjustment",
    "adverse childhood experience",
    "canada",
    "childhood adversity",
    "cleft palate",
    "co morbidity",
    "cognition disorder",
    "context",
    "correlation analysis",
    "diagnostic imaging",
    "dietary intake",
    "disruptive behavior",
    "economic",
    "ethiopia",
    "evidence base medicine",
    "expectation",
    "foster child",
    "grammar",
    "hard of hearing",
    "head circumference",
    "home numeracy",
    "infant and toddler",
    "italy",
    "language intervention",
    "learning environment",
    "leg",
    "meet analysis",
    "neighbourhood",
    "neonatal intensive care unit",
    "object relation",
    "paediatric obesity",
    "pandemic",
    "parenting stress",
    "pay info",
    "physical abuse",
    "processing speed",
    "protein human",
    "psychosocial development",
    "quality control",
    "rehabilitation",
    "reward",
    "satisfaction",
    "sci demographic",
    "singing",
    "sound",
    "time",
    "underweight",
    "aptitude",
    "auditory stimulation",
    "body height",
    "book sharing",
    "caucasian",
    "child protection",
    "clinical practice",
    "correlational study",
    "cue",
    "cumulative risk",
    "dietary supplement",
    "direct speech",
    "emotional disorder",
    "epilepsy",
    "externalizing behavior",
    "factor analysis",
    "family characteristic",
    "grandparent",
    "hospitalization",
    "impulsiveness",
    "infant extremely premature",
    "inhibition",
    "kenya",
    "language input",
    "literacy skill",
    "low income country",
    "maternal education",
    "measurement",
    "mediation analysis",
    "motor activity",
    "object attachment",
    "pakistan",
    "participation",
    "pregnancy complication",
    "psychological adjustment",
    "psychological rating scale",
    "reaction time",
    "school teacher",
    "sign language",
    "single blind method",
    "sleep quality",
    "speech production measurement",
    "symptom",
    "thinking",
    "turkey",
    "white matter",
    "year",
    "analysis of variance",
    "animal",
    "brief",
    "child day care center",
    "cognition assessment",
    "cognitive ability",
    "cognitive function",
    "cognitive skill",
    "communication aid for disabled",
    "construct validity",
    "cooperation",
    "cost benefit analysis",
    "digital technology",
    "disability",
    "disorder",
    "drug efficacy",
    "drug therapy",
    "early diagnosis",
    "education program",
    "emergent literacy",
    "emotional attachment",
    "employment",
    "english language",
    "family functioning",
    "father child relation",
    "feedback system",
    "fetal alcohol syndrome",
    "focus group",
    "functional connectivity",
    "global health",
    "group by age",
    "his",
    "hispanic americans",
    "home literacy environment",
    "incidence",
    "infant development",
    "infant nutrition",
    "joint engagement",
    "maltreatment",
    "medical history",
    "mental capacity",
    "morbidity",
    "motor dysfunction",
    "numeracy skill",
    "organization",
    "parent involvement",
    "parental belief",
    "parenting education",
    "picture book",
    "placebo",
    "population research",
    "post traumatic stress disorder",
    "preterm",
    "probability",
    "professional practice",
    "psychological resilience",
    "psychologist",
    "psychotherapy",
    "reading intervention",
    "recognition psychology",
    "secondary analysis",
    "see",
    "severity of illness index",
    "sex",
    "sleep wake disorder",
    "speech sound disorder",
    "storybook",
    "sub saharan africa",
    "tel health",
    "validation study",
    "vulnerable population",
    "we chol intelligence scale",
    "academic success",
    "adversity",
    "aetiology",
    "africa",
    "american",
    "attention deficit hyperactivity disorder",
    "auditory perception",
    "autism spectrum disorder and",
    "background television",
    "beck depression inventory",
    "bilingual",
    "body mass index",
    "brain injury traumatic",
    "child health service",
    "child nutritional physiological phenomenon",
    "child of impair parent",
    "childcare",
    "cognitive dysfunction",
    "community care",
    "compulsion",
    "concept formation",
    "counselling",
     "maternal employment",
    "maternal health",
    "maternal nutrition",
    "medical record",
    "medical record review",
    "medium",
    "method and material",
    "microcephaly",
    "missing datum",
    "morality",
    "motor function test",
    "multilevel analysis",
    "multiple regression",
    "muscle hypotonic",
    "music therapy",
    "my ligation",
    "name inventory questionnaire and rating scale",
    "narcotic analgesic agent",
    "near infrared spectroscopy",
    "nervous system development",
    "neuroscience",
    "newborn period",
    "newborn screening",
    "non intensive intervention",
    "nonparametric test",
    "nurse community health",
    "oceanic ancestry group",
    "one",
    "ontario",
    "pain",
    "parent counselling",
    "patient acceptance of health care",
    "patient engagement",
    "patient participation",
    "peru",
    "phase clinical trial",
    "playground",
    "postoperative complication",
    "prayer will syndrome",
    "predictor variable",
    "primary education",
    "primary prevention",
    "principal component analysis",
    "propensity score",
    "psychosis",
    "psychosocial",
    "psychosomatic disorder",
    "publication",
    "puerperal depression",
    "pure tone radiometry",
    "race",
    "real time polymerase chain reaction",
    "receiver operating characteristic",
    "reference value",
    "representation",
    "republic of korea",
    "research",
    "residence characteristic",
    "respiratory tract infection",
    "rest syndrome",
    "robotic",
    "safety",
    "school health service",
    "sci emotional development",
    "scoping review",
    "screen",
    "self help",
    "sleep pattern",
    "snoring",
    "social adjustment",
    "social development",
    "social medium",
    "social participation",
    "social responsiveness scale",
    "social welfare",
    "sociol emotional development",
    "somnolence",
    "south korea",
    "tablet",
    "television exposure",
    "theoretical model",
    "treatment",
    "trial",
    "trilogy",
    "trust",
    "under nutrition",
    "utilization",
    "vasomotor coordination",
    "verbal",
    "videotape recording",
    "village",
    "vomiting",
    "young",
    "aborigine",
    "abuse",
    "academic",
    "academic competence",
    "acoustic analysis",
    "acquire immune deficiency syndrome",
    "acute disease",
    "adverse outcome",
    "african",
    "algorithm",
    "all static load",
    "allele",
    "analgesic opioid",
    "analysis of covariance",
    "anatomy and histology",
    "antibiotic resistance",
    "anticipatory guidance",
    "area under the curve",
    "asian continental ancestry group",
    "asian people",
    "assertiveness",
    "assisting technology",
    "at risk",
    "attitude of health personnel",
    "auditory",
    "auditory system",
    "australian",
    "australian aborigine",
    "autobiographical memory",
    "automatic speech recognition",
    "avoidance behavior",
    "bailey iii",
    "bailey scale",
    "base",
    "beck anxiety inventory",
    "behavior modification",
    "behavior observation technique",
    "behavior rating inventory of preschool version",
    "behavior regulation",
    "behavioural outcome",
    "behavioural parent training",
    "behavioural self regulation",
    "beverage",
    "bilingual development",
    "bio marker",
    "biological model",
    "bipolar disorder",
    "birth",
    "birth order",
    "blindness",
    "body movement",
    "brain cortex",
    "brain disease",
    "brain size",
    "brain tutor",
    "breast milk",
    "bronchopulmonary dysplasia",
    "budget",
    "building block",
    "bur kina fast",
    "cancer radiotherapy",
    "canna idol",
    "cardinality",
    "care quality",
    "caregiver intervention",
    "caregiver mental health",
    "caregiver speech",
    "castro esophageal reflux",
    "cd",
    "center for epidemiological study depression scale",
    "cerebral malaria",
    "cerebrovascular accident",
    "chaos",
    "chemotherapy",
    "child adjustment",
    "child adopt",
    "child bear",
    "child behavior questionnaire",
    "child development disorder pervasive",
    "child interaction",
    "child outcome",
    "child protective service",
    "child with hearing loss",
    "childhood injury",
    "childhood trauma",
    "chilean",
    "chinese parent",
    "choice behavior",
    "chromosome human pair",
    "circadian rhythm",
    "classification",
    "clinical psychology",
    "club be",
    "coaching",
    "cocaine",
    "coding",
    "cognitive and",
    "cognitive functioning",
    "cognitive load",
    "cognitive performance",
    "cognitive rehabilitation",
    "cognitive therapy",
    "college",
    "combine modality therapy",
    "communication and symbolic behavior scale",
    "communicative development inventory",
    "community base participatory research",
    "computational thinking",
    "confounding variable",
    "congenital malformation",
    "connectivity",
    "contextual risk",
    "contingency",
    "contingent",
    "control clinical trial topic",
    "conversation analysis",
    "conversational turn",
    "copy number variation",
    "corpus",
    "corpus call sum",
    "correlation coefficient",
    "cortical thickness brain",
    "cost",
    "cross cultural research",
    "culturally competent care",
    "dam in to",
    "deaf and hard of hearing",
    "deaf child",
    "default mode network",
    "delay of gratification",
    "deletion syndrome",
    "deli plan system",
    "dementia assessment",
    "dental health",
    "depression anxiety and stress scale",
    "deterioration",
    "determinant",
    "developmental outcome",
    "developmental psychopathology",
    "developmental trajectory",
    "diagnostic value",
    "dialogue book reading",
    "diet therapy",
    "dietary pattern",
    "dietitian",
    "differential ability scale",
    "disability assessment",
    "disease assessment",
    "disease surveillance",
    "disparity",
    "distract ability",
    "drinking",
    "drinking behavior",
    "drug exposure",
    "drug resistant epilepsy",
    "dyadic synchrony",
    "dysphagia",
    "early care and education",
    "early education",
    "early experience",
    "early language intervention",
    "early match",
    "early mathematic",
    "early year education",
    "eating disorder",
    "eating habit",
    "economic evaluation",
    "edinburgh postnatal depression scale",
    "educational measurement",
    "effectiveness",
    "electronic medical record",
    "electronic medium",
    "energy intake",
    "enhance milieu teaching",
    "entire tropical therapy",
    "environmental enrichment",
    "environmental risk",
    "evaluation",
    "executive dysfunction",
    "experimental design",
    "expressive vocabulary test",
    "externalizing",
    "extremely premature birth",
    "eye tracking technology",
    "face",
    "facilitation",
    "fair",
    "family check up",
    "family intervention",
    "family process",
    "family risk",
    "fast food",
    "fatty acid",
    "feedback psychological",
    "feeding difficulty",
    "feeding practice",
    "fever",
    "final ukraine",
    "financial stress",
    "finger",
    "fluency",
    "fluid reasoning",
    "food frequency questionnaire",
    "food intake",
    "food supply",
    "friend",
    "frontal lobe",
    "functional disease",
    "functional status assessment",
    "funding",
    "gambia",
    "generalize anxiety disorder",
    "genetic predisposition to disease",
    "genetic variation",
    "go no go task",
    "gray matter",
    "haemoglobin blood level",
    "hand",
    "health center",
    "health economic",
    "health hazard",
    "health policy",
    "healthy lifestyle",
    "heredity",
    "hierarchical clustering",
    "high income country",
    "high income group",
    "high risk behavior",
    "hippocampus",
    "his aid",
    "icon city",
    "illinois",
    "immunosuppressive treatment",
    "in",
    "in service training",
    "index",
    "inequality",
    "infant care",
    "infantile spasm",
    "infectious disease",
    "inference",
    "inflammation",
    "inheritance",
    "input quality",
    "input quantity",
    "instability",
    "institutionalized child",
    "integrate health care system",
    "integrate intervention",
    "intelligibility",
    "intensive care unit neonatal",
    "internalizing behavior",
    "international cooperation",
    "internationality",
    "ipad",
    "ireland",
    "iron deficiency",
    "italian citizen",
    "japan",
    "joint",
    "latin america",
    "learn",
    "leave behind child",
    "linear growth",
    "linguistic competency",
    "linguistic precocity",
    "literature",
    "lock own",
    "long term memory",
    "longitudinal analysis",
    "low see",
    "low socioeconomic status",
    "mass medium",
    "massage",
    "match anxiety",
    "maternal",
    "maternal child health service",
    "maternal scaffolding",
    "mathematical ability",
    "maximum likelihood method",
    "measurement invariance",
    "mediator",
    "medical care",
    "medical information",
    "medical research",
    "medical society",
    "memory test",
    "mental development",
    "mental state language",
    "mental status and dementia test",
    "mentoring",
    "methamphetamine",
    "mexican",
    "mexican american",
    "mind",
    "mind mindedness",
    "mini mental state examination",
    "minority group",
    "miss mutation",
    "mobile learning",
    "mobile phone",
    "model psychological",
    "model theoretical",
    "money",
    "monitoring",
    "mood disorder",
    "morphology",
    "motor competence",
    "mouse",
    "movement",
    "muscle mass",
    "mutation",
    "my clonu epilepsy",
    "myopia",
    "name",
    "natural history",
    "near anatomy",
    "near cognition",
    "near cognitive disorder",
    "near feedback",
    "near pathology",
    "negative emotion",
    "neonatology",
    "nerve net",
    "nervous system parameter",
    "neural pathway",
    "neurobiology",
    "neurophysiology",
    "new south wale",
    "nicotine",
    "nigeria",
    "no rem sleep",
    "nomenclature",
    "non governmental organization",
    "nonverbal reasoning",
    "northern territory",
    "number competence",
    "nursery",
    "nursery school",
    "nutritional deficiency",
    "nutritional disorder",
    "observation",
    "observational method",
    "odd ratio",
    "ohio",
    "outcome measure",
    "pad",
    "paediatric intensive care unit",
    "paediatric sleep questionnaire",
    "parallel design",
    "parent belief",
    "parent engagement",
    "parent implement",
    "parent intervention",
    "parent knowledge",
    "parental depression",
    "parental expectation",
    "parental investment",
    "parental language input",
    "parental mental health",
    "parental perception",
    "paternal behavior",
    "patient care",
    "patient discharge",
    "patient satisfaction",
    "pattern",
    "perceive stress scale",
    "phobia",
    "phonological development",
    "phonological skill",
    "physical health",
    "physical performance",
    "physicians role",
    "planning",
    "plasticity",
    "play therapy",
    "positive parenting",
    "postpartum period",
    "practice guideline as topic",
    "prefrontal cortex",
    "prenatal cocaine exposure",
    "prenatal period",
    "preterm infant",
    "preventive medicine",
    "print exposure",
    "print knowledge",
    "program development",
    "protein",
    "protein serine threonine kinase",
    "protocol compliance",
    "psychological model",
    "psychosocial withdrawal",
    "publication bias",
    "qualitative method",
    "quality of health care",
    "randomize trial",
    "rapid automatize naming",
    "read aloud",
    "reading fluency",
    "recurrent disease",
    "registration",
    "regulation",
    "relative clause",
    "religion",
    "reminiscing",
    "research ethic",
    "respiratory failure",
    "responsively",
    "right hemisphere",
    "risk benefit analysis",
    "sampling",
    "scaffold",
    "schizophrenia",
    "school adjustment",
    "school age",
    "school nursery",
    "scientific literature",
    "screening test",
    "second trimester pregnancy",
    "sedentary behavior",
    "self direct learning",
    "sensory stimulation",
    "serotonin uptake inhibitor",
    "severe acute respiratory syndrome corona virus",
    "severe cyclonic epilepsy in infancy",
    "sex ratio",
    "sexual abuse",
    "share storybook reading",
    "short form",
    "short term",
    "shyness",
    "sickle cell disease",
    "simple view",
    "sleep duration",
    "sleep initiation and maintenance disorder",
    "sleep latency",
    "small for gestational age",
    "social",
    "social cognitive development",
    "social emotional",
    "social emotional development",
    "social engagement",
    "social interaction",
    "social phobia",
    "social worker",
    "socioeconomic condition",
    "socioeconomic disadvantage",
    "sound detection",
    "south african",
    "spa",
    "spain",
    "spanish language",
    "specific language impairment",
    "spectrum",
    "speech acoustic",
    "speech discrimination",
    "speech generating device",
    "speech language therapy",
    "stakeholder engagement",
    "stanford bidet intelligence scale",
    "statistic",
    "still face",
    "story comprehension",
    "stress assessment",
    "structured interview",
    "superior longitudinal fasciculus",
    "surveillance",
    "sweden",
    "symbolism",
    "symptom checklist",
    "syntax",
    "synthesis",
    "talking",
    "task performance and analysis",
    "teacher education",
    "teen mother",
    "tel practice",
    "tennessee",
    "tertiary care center",
    "test of variable of attention",
    "text messaging",
    "third trimester pregnancy",
    "time series analysis",
    "toddler language",
    "tool use",
    "trail making test",
    "trans cultural care",
    "transition",
    "translation",
    "trauma",
    "troop test",
    "twin study",
    "urine sampling",
    "velocity",
    "verbal ability",
    "verbalization",
    "video",
    "video game",
    "vietnam",
    "visual impairment",
    "visual stimulation",
    "vitamin",
    "vocabulary growth",
    "voice quality",
    "we chol adult intelligence scale",
    "whole home sequencing",
    "williams syndrome",
    "wisconsin card sorting test",
    "wordless picture book",
    "workshop",
    "writing support",
    "zambia",
    "zika virus",
    "zinc",
    "academic language",
    "access",
    "achievement gap",
    "acoustic stimulation",
    "act graph",
    "activation",
    "activity",
    "adherence",
    "adjective",
    "adjustment problem",
    "adolescent development",
    "adoptive parent",
    "adult child",
    "adult direct speech",
    "adverse effect",
    "affective symptom",
    "afford dance in the for motor development infant scale",
    "afghanistan",
    "africa south of the sahara",
    "african americans",
    "aftercare",
    "age child",
    "age of onset",
    "aged and over",
    "agency",
    "aggressive behavior",
    "aggressiveness",
    "aid use",
    "alcohol drinking",
    "alcoholism",
    "allergy",
    "alternative communication",
    "american indian",
    "amygdala",
    "an",
    "anaemia iron deficiency",
    "analogy",
    "analytic method",
    "animal experiment",
    "animal model",
    "animal tissue",
    "anthropology cultural",
    "anti bacterial agent",
    "anti his agent",
    "anti human immunodeficiency virus agent",
    "anti infective agent",
    "anti seizure medication",
    "antibiotic",
    "app in",
    "appetite",
    "approximate number system",
    "apraxia",
    "apron study",
    "arizona",
    "arm",
    "asperger syndrome",
    "ataxia",
    "attention problem",
    "attention test",
    "attentional control",
    "attitude to illness",
    "audiologist",
    "auditory attention",
    "auditory memory",
    "auditory orientation",
    "australia and new zealand",
    "australian study",
    "authority",
    "auto mutilation",
    "automate vocal analysis",
    "autonomic nervous system",
    "aversion",
    "basal ganglion",
    "be latin",
    "be numeracy skill",
    "bedtime"

]

# Función para eliminar palabras clave específicas y retornar una cadena
def eliminar_palabras_clave(column):
    # Convertir la lista de palabras clave a eliminar a minúsculas
    palabras_clave_a_eliminar_lower = [palabra.lower() for palabra in palabras_clave_a_eliminar]
    
    def process_cell(cell):
        # Si la celda es una cadena, la dividimos en una lista usando el separador ';'
        if isinstance(cell, str):
            terminos = [termino.strip() for termino in cell.split(';') if termino.strip()]
        # Si ya es una lista, la usamos directamente
        elif isinstance(cell, list):
            terminos = [str(termino).strip() for termino in cell if str(termino).strip()]
        else:
            terminos = []
        # Filtrar los términos que, al pasar a minúsculas, estén en la lista a eliminar
        terminos_filtrados = [termino for termino in terminos if termino.lower() not in palabras_clave_a_eliminar_lower]
        # Unir la lista filtrada en una cadena usando '; ' como separador
        return '; '.join(terminos_filtrados)

    return column.apply(process_cell)

# Aplicar la función a las columnas "Index Keywords" y "Author Keywords"
df['Index Keywords'] = eliminar_palabras_clave(df['Index Keywords'])
#df['bothKeywords'] =  eliminar_palabras_clave(df['bothKeywords'])
df['Author Keywords'] = eliminar_palabras_clave(df['Author Keywords'])
# Guardar el DataFrame filtrado en un nuevo archivo CSV

# Construir listado global normalizado
all_terms = pd.concat([
    df['Index Keywords'].dropna(),
    df['Author Keywords'].dropna()
]).str.split(';').explode().str.strip()

# Frecuencia sobre versión normalizada
freq = all_terms.str.lower().value_counts()
keep_norm = set(freq[freq > 1].index)

def filter_unique(cell):
    if not isinstance(cell, str):
        return ""
    terms = [t.strip() for t in cell.split(';') if t.strip()]
    filtered = [t for t in terms if t.lower() in keep_norm]
    return '; '.join(filtered)

df['Index Keywords'] = df['Index Keywords'].apply(filter_unique)
df['Author Keywords'] = df['Author Keywords'].apply(filter_unique)
# Guardar el DataFrame filtrado en un nuevo archivo CSV
#df.to_csv("G:\\Mi unidad\\2024\\SCientoPy\\ScientoPy\\dataPre\\papersPreprocessed.csv", index=False)

df.to_csv( r"G:\Mi unidad\2025\master karla mora\new article scopus\data\datawos_scopusdelete.csv", index=False)
print("Palabras clave específicas eliminadas y nuevo archivo guardado.")
