import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("G:\\Mi unidad\\2024\\Master JAVIER ANDRES CHILIQUINGA AMAYA\\IDH Bibliometría\\data\\wos_scopus.csv")

   
# Lista de palabras clave a eliminar (en minúsculas)
palabras_clave_a_eliminar = [
   "china", "covid-19", "south africa", "india", "linear matrix inequality (lmi)", 
    "sub-saharan africa", "digital divide", "migration", "adolescents", "africa", 
    "democracy", "ethiopia", "indonesia", "spain", "vietnam", "australia", 
    "concentration index", "corruption", "housing", "institutional quality", 
    "quantile regression", "tanzania", "accessibility", "brazil", "decentralization", 
    "environment", "ethnicity", "heterogeneity", "labour market", "lyapunov method", 
    "mental health", "mortality", "policy", "resilience", "segregation", "agriculture", 
    "bangladesh", "child health", "children", "decomposition", "decomposition analysis", 
    "deprivation", "developing countries", "disability", "discrimination", 
    "early childhood education", "economics", "efficiency", "epidemiology", "ghana", 
    "gini coefficient", "gmm", "internet", "local government", "malaysia", 
    "neoliberalism", "redistribution", "school readiness", "stability analysis", 
    "variational inequality", "violence against women", "air pollution", "bi-capacity", 
    "capacity building", "channel capacity", "climate change", "convex optimization", 
    "decentralisation", "depression", "difference-in-differences", "economic freedom", 
    "education reform", "family background", "foreign direct investment", "funding", 
    "global health", "hiv", "ict", "ideology", "income distribution", "inequalities", 
    "innovation", "iran", "justice", "land", "leadership", "life expectancy", 
    "local stability", "mexico", "mobility", "multidimensional poverty", "optimization", 
    "oral health", "panel data", "panel data analysis", "participation", "philippines", 
    "planning", "policy analysis", "political economy", "political participation", 
    "polytopic uncertainty", "poverty alleviation", "preschool", "primary education", 
    "public policy", "race", "relaxation", "right to education", "rural china", 
    "rural development", "school", "schooling", "sdgs", "secondary education", 
    "social cohesion", "social determinants", "social determinants of health", 
    "social infrastructure", "social investment", "solidarity", "spatial analysis", 
    "spatial heterogeneity", "spatial inequality", "subjective well-being", "taxation", 
    "teacher training", "theil index", "uganda", "universal health coverage", "urban", 
    "urbanisation", "women", "women empowerment", "academic performance", 
    "achievement gap", "adaptive capacity", "adolescent", "antagonism", "ardl", 
    "asian countries", "autonomy", "bibliometric study", "bipolar choquet integral", 
    "bipolar shilkret integral", "bipolar sugeno integral", "cancer", "capability approach", 
    "carbon emissions", "caste", "child mortality", "childcare", "choice disability", 
    "chronic illness", "circular economy", "clil", "cognitive skills", "cohort studies", 
    "colombia", "community forestry", "comparative study", "convergence", 
    "convex function", "corporate social responsibility", "crime rate", 
    "critical consciousness", "cross-national", "culture", "cumulative advantage", 
    "curriculum", "data envelopment analysis (dea)", "dental caries", 
    "developmental state", "developmental vulnerability", "digital inequality", 
    "digital skills", "disadvantage", "distributional effects", "districts", "diversity", 
    "domain of attraction (da)", "drivers", "driving factors", "e24", 
    "early childhood development", "early marriage", "earthquake", "east africa", 
    "education investment", "education quality", "education system", "educational equity", 
    "educational resources", "elasticity", "energy", "energy efficiency", "energy poverty", 
    "entrepreneurship", "environmental quality", "environmental sustainability", "ethics", 
    "ethnic minority", "european union", "evaluation", "family", "fdi", "fertility", 
    "financial inclusion", "fiscal decentralization", "fiscal federalism", 
    "food insecurity", "foundational skills", "gdp", "gender differences", "gender gap", 
    "gender wage gap", "generalized method of moments (gmm)", "geographically weighted regression", 
    "gini index", "globalisation", "globalization", "government", "government expenditures", 
    "grid-connected inverter", "growth model", "h-infinity performance", "h54", 
    "health disparities", "health insurance", "health outcome", "healthcare financing", 
    "height", "higher education institutions", "higher education policy", "hong kong", 
    "hukou", "human opportunity index", "icts", "immigration", "inclusion", 
    "inclusive education", "indicators", "indigenous", "infectious disease", 
    "internet access", "intimate partner violence", "jensen's inequality", "kazakhstan", 
    "kenya", "knowledge economy", "kuznets curve", "labor market", "labor supply", 
    "land reform", "land use", "language", "learning outcomes", "lifelong learning", 
    "linear matrix inequality", "linear time-invariant (lti) system", "living conditions", 
    "living labs", "longitudinal data", "lyapunov function", "macroeconomics", 
    "malnutrition", "market transformation", "marketization", "marriage", 
    "maternal and child health", "measurement", "minimum wage", "monetary policy", 
    "multicollinearity", "municipalities", "natural disasters", "neo-liberalism", 
    "network analysis", "new-type urbanization", "nigeria", "non-farm", "nonlinear systems", 
    "nutrition", "o53", "obesity", "off-farm", "older people", "pakistan", "parenting", 
    "perception", "pisa", "pluralism", "pm2", "political decentralisation", "politics", 
    "population", "population aging", "preferences", "preterm birth", "primary care", 
    "primary school", "principal component analysis", "privatisation", 
    "probability transition matrix", "professional development", "public education", 
    "public expenditure", "public opinion", "public services", "public spending", 
    "quality education", "racial inequality", "refugees", "regional differences", 
    "regional disparities", "regional income inequality", "regulation", "remittances", 
    "renewable energy", "residential mobility", "roma", "rural education", "russia", 
    "sanitation", "scale", "scholarships", "schoolchildren", "schools", "science", 
    "scotland", "shadow education", "shocks", "skills", "skills development", 
    "social cohesion", "social innovation", "social infrastructure", "solidarity", 
    "spatial analysis", "spatial heterogeneity", "spatial inequality", 
    "subjective well-being", "taxation", "teacher training", "theil index", "uganda", 
    "universal health coverage", "urban", "urbanisation", "women", "women empowerment", 
    "academic performance", "achievement gap", "adaptive capacity", "adolescent", 
    "antagonism", "ardl", "asian countries", "autonomy", "bibliometric study", 
    "bipolar choquet integral", "bipolar shilkret integral", "bipolar sugeno integral", 
    "cancer", "capability approach", "carbon emissions", "caste", "child mortality", 
    "childcare", "choice disability", "chronic illness", "circular economy", "clil", 
    "cognitive skills", "cohort studies", "colombia", "community forestry", 
    "comparative study", "convergence", "convex function", "corporate social responsibility", 
    "crime rate", "critical consciousness", "cross-national", "culture", "cumulative advantage", 
    "curriculum", "data envelopment analysis (dea)", "dental caries", "developmental state", 
    "developmental vulnerability", "digital inequality", "digital skills", "disadvantage", 
    "distributional effects", "districts", "diversity", "domain of attraction (da)", 
    "drivers", "driving factors", "e24", "early childhood development", "early marriage", 
    "earthquake", "east africa", "education investment", "education quality", "education system", 
    "educational equity", "educational resources", "elasticity", "energy", "energy efficiency", 
    "energy poverty", "entrepreneurship", "environmental quality", "environmental sustainability", 
    "ethics", "ethnic minority", "european union", "evaluation", "family", "fdi", "fertility", 
    "financial inclusion", "fiscal decentralization", "fiscal federalism", "food insecurity",
    "fiscal decentralization", "fiscal federalism", "food insecurity", "foundational skills", "gdp", 
    "gender differences", "gender gap", "gender wage gap", "generalized method of moments (gmm)", 
    "geographically weighted regression", "gini index", "globalisation", "globalization", "government", 
    "government expenditures", "grid-connected inverter", "growth model", "h-infinity performance", "h54", 
    "health disparities", "health insurance", "health outcome", "healthcare financing", "height", 
    "higher education institutions", "higher education policy", "hong kong", "hukou", "human opportunity index", 
    "icts", "immigration", "inclusion", "inclusive education", "indicators", "indigenous", "infectious disease", 
    "internet access", "intimate partner violence", "jensen's inequality", "kazakhstan", "kenya", "knowledge economy", 
    "kuznets curve", "labor market", "labor supply", "land reform", "land use", "language", "learning outcomes", 
    "lifelong learning", "linear matrix inequality", "linear time-invariant (lti) system", "living conditions", 
    "living labs", "longitudinal data", "lyapunov function", "macroeconomics", "malnutrition", "market transformation", 
    "marketization", "marriage", "maternal and child health", "measurement", "minimum wage", "monetary policy", 
    "multicollinearity", "municipalities", "natural disasters", "neo-liberalism", "network analysis", 
    "new-type urbanization", "nigeria", "non-farm", "nonlinear systems", "nutrition", "o53", "obesity", 
    "off-farm", "older people", "pakistan", "parenting", "perception", "pisa", "pluralism", "pm2", 
    "political decentralisation", "politics", "population", "population aging", "preferences", "preterm birth", 
    "primary care", "primary school", "principal component analysis", "privatisation", "probability transition matrix", 
    "professional development", "public education", "public expenditure", "public opinion", "public services", 
    "public spending", "quality education", "racial inequality", "refugees", "regional differences", 
    "regional disparities", "regional income inequality", "regulation", "remittances", "renewable energy", 
    "residential mobility", "roma", "rural education", "russia", "sanitation", "scale", "scholarships", 
    "schoolchildren", "schools", "science", "scotland", "shadow education", "shocks", "skills", "skills development", 
    "social cohesion", "social innovation", "social infrastructure", "solidarity", "spatial analysis", 
    "spatial heterogeneity", "spatial inequality", "subjective well-being", "taxation", "teacher training", 
    "theil index", "uganda", "universal health coverage", "urban", "urbanisation", "women", "women empowerment", 
    "academic performance", "achievement gap", "adaptive capacity", "adolescent", "antagonism", "ardl", 
    "asian countries", "autonomy", "bibliometric study", "bipolar choquet integral", "bipolar shilkret integral", 
    "bipolar sugeno integral", "cancer", "capability approach", "carbon emissions", "caste", "child mortality", 
    "childcare", "choice disability", "chronic illness", "circular economy", "clil", "cognitive skills", 
    "cohort studies", "colombia", "community forestry", "comparative study", "convergence", "convex function", 
    "corporate social responsibility", "crime rate", "critical consciousness", "cross-national", "culture", 
    "cumulative advantage", "curriculum", "data envelopment analysis (dea)", "dental caries", "developmental state", 
    "developmental vulnerability", "digital inequality", "digital skills", "disadvantage", "distributional effects", 
    "districts", "diversity", "domain of attraction (da)", "drivers", "driving factors", "e24", 
    "early childhood development", "early marriage", "earthquake", "east africa", "education investment", 
    "education quality", "education system", "educational equity", "educational resources", "elasticity", 
    "energy", "energy efficiency", "energy poverty", "entrepreneurship", "environmental quality", 
    "environmental sustainability", "ethics", "ethnic minority", "european union", "evaluation", "family", "fdi", 
    "fertility", "financial inclusion",
    "marriage", "maternal and child health", "measurement", "minimum wage", "monetary policy", 
    "multicollinearity", "municipalities", "natural disasters", "neo-liberalism", "network analysis", 
    "new-type urbanization", "nigeria", "non-farm", "nonlinear systems", "nutrition", "o53", "obesity", 
    "off-farm", "older people", "pakistan", "parenting", "perception", "pisa", "pluralism", "pm2", 
    "political decentralisation", "politics", "population", "population aging", "preferences", 
    "preterm birth", "primary care", "primary school", "principal component analysis", "privatisation", 
    "probability transition matrix", "professional development", "public education", "public expenditure", 
    "public opinion", "public services", "public spending", "quality education", "racial inequality", 
    "refugees", "regional differences", "regional disparities", "regional income inequality", "regulation", 
    "remittances", "renewable energy", "residential mobility", "roma", "rural education", "russia", 
    "sanitation", "scale", "scholarships", "schoolchildren", "schools", "science", "scotland", 
    "shadow education", "shocks", "skills", "skills development", "social cohesion", "social innovation", 
    "social infrastructure", "solidarity", "spatial analysis", "spatial heterogeneity", "spatial inequality", 
    "subjective well-being", "taxation", "teacher training", "theil index", "uganda", "universal health coverage", 
    "urban", "urbanisation", "women", "women empowerment", "academic performance", "achievement gap", 
    "adaptive capacity", "adolescent", "antagonism", "ardl", "asian countries", "autonomy", 
    "bibliometric study", "bipolar choquet integral", "bipolar shilkret integral", "bipolar sugeno integral", 
    "cancer", "capability approach", "carbon emissions", "caste", "child mortality", "childcare", 
    "choice disability", "chronic illness", "circular economy", "clil", "cognitive skills", "cohort studies", 
    "colombia", "community forestry", "comparative study", "convergence", "convex function", 
    "corporate social responsibility", "crime rate", "critical consciousness", "cross-national", "culture", 
    "cumulative advantage", "curriculum", "data envelopment analysis (dea)", "dental caries", 
    "developmental state", "developmental vulnerability", "digital inequality", "digital skills", 
    "disadvantage", "distributional effects", "districts", "diversity", "domain of attraction (da)", 
    "drivers", "driving factors", "e24", "early childhood development", "early marriage", "earthquake", 
    "east africa", "education investment", "education quality", "education system", "educational equity", 
    "educational resources", "elasticity", "energy", "energy efficiency", "energy poverty", 
    "entrepreneurship", "environmental quality", "environmental sustainability", "ethics", "ethnic minority", 
    "european union", "evaluation", "family", "fdi", "fertility", "financial inclusion", 
    "fiscal decentralization", "fiscal federalism", "food insecurity", "foundational skills", "gdp", 
    "gender differences", "gender gap", "gender wage gap", "generalized method of moments (gmm)", 
    "geographically weighted regression", "gini index", "globalisation", "globalization", "government", 
    "government expenditures", "grid-connected inverter", "growth model", "h-infinity performance", "h54", 
    "health disparities", "health insurance", "health outcome", "healthcare financing", "height", 
    "higher education institutions", "higher education policy", "hong kong", "hukou", "human opportunity index", 
    "icts", "immigration", "inclusion", "inclusive education", "indicators", "indigenous", "infectious disease", 
    "internet access", "intimate partner violence", "jensen's inequality", "kazakhstan", "kenya", "knowledge economy", 
    "kuznets curve", "labor market", "labor supply", "land reform", "land use", "language", "learning outcomes", 
    "lifelong learning", "linear matrix inequality", "linear time-invariant (lti) system", "living conditions", 
    "living labs", "longitudinal data", "lyapunov function", "macroeconomics", "malnutrition", 
    "market transformation", "marketization"
    
]
# Función para eliminar palabras clave específicas
def eliminar_palabras_clave(column):
    # Rellenar valores NaN con una cadena vacía
    column = column.fillna('')
    # Convertir los valores de la columna a minúsculas y dividir en listas
    palabras = column.str.lower().str.split(';')
    # Convertir la lista de palabras clave a eliminar a minúsculas
    palabras_clave_a_eliminar_lower = [palabra.lower() for palabra in palabras_clave_a_eliminar]
    # Filtrar las palabras clave no deseadas
    palabras_filtradas = palabras.apply(lambda x: [palabra.strip() for palabra in x if palabra.strip() not in palabras_clave_a_eliminar_lower])
    # Unir las palabras filtradas de nuevo en un string separado por "; "
    return palabras_filtradas.str.join('; ')

# Aplicar la función a las columnas "Index Keywords" y "Author Keywords"
df['Index Keywords'] = eliminar_palabras_clave(df['Index Keywords'])
df['Author Keywords'] = eliminar_palabras_clave(df['Author Keywords'])

# Guardar el DataFrame filtrado en un nuevo archivo CSV

# Guardar el DataFrame filtrado en un nuevo archivo CSV
df.to_csv("G:\\Mi unidad\\2024\\Master JAVIER ANDRES CHILIQUINGA AMAYA\\IDH Bibliometría\\data\\wos_scopus.csv", index=False)

print("Palabras clave específicas eliminadas y nuevo archivo guardado.")
